### ISSUE TITLE
Predictions with new data: error message "Error in LFix + Reduce("+", LRan) : non-conformable arrays"

### ISSUE THREAD

**Issue by gaiteiro** [hmsc-r/HMSC#102]
Good morning,

I built and cross-validated a spatial model on a grid with plant species records and am trying to exrtend the model to predict species presence/absence over a larger grid that includes unsampled grid squares.
```r
nChains = 2
thin = 5
samples = 1000 
transient = 500*thin
verbose = 50*thin
X<- read.csv('C:/Users/smith/Documents/X180_500.csv', header=T)
y <- read.csv('C:/Users/smith/Documents/Y180_500.csv', header=T)
Y=as.matrix(y)
n <- nrow(X)
studyDesign = data.frame(sample = as.factor(1:n))
xycoords <- X[c("xcoord", "ycoord")]
rL.spatial = HmscRandomLevel(sData = xycoords)
rL.spatial = setPriors(rL.spatial,nfMin=1,nfMax=1)
fit = Hmsc(Y=Y, XData=X, XFormula=~NGcostmean + elev_range + X02_cecmean + X07_t10mean + X13_thrmmea + 
           X15_trimean + X17_fparmea + X18_laimean + X29_soc1mea + X36_sq3mean + X38_sq5mean + X43_bio7mea,
         studyDesign=studyDesign, ranLevels=list("sample"=rL.spatial), distr="probit")
fit= sampleMcmc(fit, thin = thin, samples = samples, transient = transient,
                       nChains = nChains, verbose = verbose, updater=list(GammaEta=FALSE))

x2 <- read.csv('C:/Users/smith/Documents/nnMaxEnt3/1820_grids_coords.csv', header=T)
n <- nrow(x2)
studyDesign = data.frame(sample = as.factor(1:n))
xycoords <- x2[c("xcoord", "ycoord")]
rL.spatial = HmscRandomLevel(sData = xycoords)
rL.spatial = setPriors(rL.spatial,nfMin=1,nfMax=1)
predict(object=fit, XData=x2, ranLevels=list("sample"=rL.spatial))

Error in LFix + Reduce("+", LRan) : non-conformable arrays
```
I seem to have trouble posting a zipped version of the .rds fitted model. However, here is the data (all the locations have full data for the selected covariates, so no NAs)

New locations and covariates: [1820_grids_coords.csv](https://github.com/hmsc-r/HMSC/files/6675196/1820_grids_coords.csv)
Original presence-absence of species: [Y180_500.csv](https://github.com/hmsc-r/HMSC/files/6675262/Y180_500.csv)
Original locations and covariates: [X180_500.csv](https://github.com/hmsc-r/HMSC/files/6675264/X180_500.csv)

Another query: is it possible to set a covariate in the model to zero when making predictions, to 'adjust' for that factor? What I am doing is predicting total species richness (not presence of individual species) in 25km grids across the island of New Guinea. I have a covariate (NGcostmean) for a cost-distance raster which models the difficulty of access to a region (as a proxy for sampling intensity). I would like to see what happens when I set that to zero, i.e. assume that all areas are equally accessible and predict species richness from the environmental factors alone. Does that make sense...?

Best regards,
Michael

**Comment by jarioksa** [comment]
This looks like the same issue that was discussed in issue #33. That #33 is a very long and rambling issue that has long departed from its starting point, but the last messages there deal with `predict` problems giving that exact error message. In that case the problem was that the new data (in your case `x2` contained missing values `NA` that are not accepted in predictor variables. Please check your data.

As of yesterday, **Hmsc**  in github tries to detect the missing values and give a more informative error message than "non-conformable arrays". (The arrays are non-conformable, because observations with missing values are removed from fixed effects but not from random effects.)

**Comment by gaiteiro** [comment]
Apologies - my mistake. I've filled in the NAs so any(is.na(x2)) returns FALSE. 

I still get the error message though...

I'll have a look at #33 to see what I can find. Thanks!

**Comment by gaiteiro** [comment]
Hi,

I installed the Github version using install_github("hmsc-r/HMSC")

any(is.na(x2)) returns FALSE when applied to the 'new data' dataframe with interpolated data:
[1820_grids_coords.csv](https://github.com/hmsc-r/HMSC/files/6680796/1820_grids_coords.csv)

...however, I still get this error:
> predict(object=fit, XData=x2, ranLevels=list("sample"=rL.spatial))
Error in LFix + Reduce("+", LRan) : non-conformable arrays

The new data file consists of both the old locations (coordinates and covariates) plus some new locations. I also tried loading in only the new locations, thinking that maybe overlap between new and old locations wasn't allowed, but got the same error.

I'm quite new to this so hope you'll excuse any more beginner's mistakes. The vignettes are very helpful tutorials but I can't find anything on prediction with new data?

**Comment by gaiteiro** [comment]
I've sorted it out - code should have been:

pred = Hmsc:::predict.Hmsc(fit, XData = data.frame(x2), type = "response", studyDesign = studyDesign, 
                           ranLevels=list("sample"=rL.spatial), expected = TRUE)

**Comment by grahamfrank** [comment]
For anyone who ends up on this thread, I had the same error using predict "Error in LFix + Reduce("+", LRan) : non-conformable arrays" if I tried to use scale() within my specification of XFormula. I only wanted to scale specific variables since some were categorical and one is an offset, so my solution was to scale them in XData instead.
