### ISSUE TITLE
Can I specify interactions between RRR covariates and "normal" covariates?

### ISSUE THREAD

**Issue by andburch** [hmsc-r/HMSC#108]
If I have several environmental covariates I want to include as normal predictors in the model and several environmental covariates I want to distill into a single linear combination (through RRR), is there a way I can specify an interaction term between one of the "normal" predictors and the combined RRR covariate?

**Comment by ovaskain** [comment]
Such an interaction has not been implemented (but is an interesting suggestion!).

O2

From: Andrew T Burchill ***@***.***>
Sent: tiistai 6. heinäkuuta 2021 2:11
To: hmsc-r/HMSC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hmsc-r/HMSC] Can I specify interactions between RRR covariates and "normal" covariates? (#108)


If I have several environmental covariates I want to include as normal predictors in the model and several environmental covariates I want to distill into a single linear combination (through RRR), is there a way I can specify an interaction term between one of the "normal" predictors and the combined RRR covariate?
