### ISSUE TITLE
Access to code used in Ovaskainen et al. 2017? (Ecology Letters)

### ISSUE THREAD

**Issue by andburch** [hmsc-r/HMSC#109]
As a new HMSC user, I find code examples to be incredibly useful in helping with my own project. Along those lines, is the code used in [Ovaskainen et al 2017](https://onlinelibrary.wiley.com/doi/10.1111/ele.12757) publicly available anywhere? If not, what are the chances of uploading that code any time soon? I understand that's probably unlikely, but I can always dream.

I think seeing how the plots were made, how the different data were used, etc. would be very illuminating for new users!

**Comment by ovaskain** [comment]
Hi Andrew,

Have you gone through the vignettes? As well as the couple of example from the book that are published as executable code here: https://www2.helsinki.fi/en/researchgroups/statistical-ecology/hmsc

I think these are the best executable codes we provide. Some published papers come also with code, but Ovaskainen et al. 2017 came before the main R-package so its codes would not work with the current versions.

Best,

O2

From: Andrew T Burchill ***@***.***>
Sent: keskiviikko 14. heinäkuuta 2021 21:20
To: hmsc-r/HMSC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hmsc-r/HMSC] Access to code used in Ovaskainen et al. 2017? (Ecology Letters) (#109)


As a new HMSC user, I find code examples to be incredibly useful in helping with my own project. Along those lines, is the code used in Ovaskainen et al 2017<https://onlinelibrary.wiley.com/doi/10.1111/ele.12757> publicly available anywhere? If not, what are the chances of uploading that code any time soon? I understand that's probably unlikely, but I can always dream.

I think seeing how the plots were made, how the different data were used, etc. would be very illuminating for new users!

**Comment by andburch** [comment]
Thank you!

**Comment by hmstorecenter-com** [comment]
Thank you for all the positive comments from you. I take all of your explanations Openly. and Be pleased to receive and hear new Ideas. I will try my best to improve the quality of the existing code.

@hmsc-r
