### ISSUE TITLE
Question about using XSelect on species subgroups or just specifying traits...

### ISSUE THREAD

**Issue by andburch** [hmsc-r/HMSC#110]
I have a dumb, conceptual question: what is the use-case of selectively applying some covariates to a subgroup of species. In reference to selecting variables only for subgroups of species:
> One may hypothesise that species with different trait categories (e.g. species from different guilds) or from different taxonomical groups respond to different sets of variables.

But isn't that the whole point of having trait data? Shouldn't "guild" be included as one of the traits, and then the model will fit various responses between the different values of "guild" and different covariates? I'm curious about the differences in these two approaches and I'm wondering what I'm missing here.

(Also it looks like this quote includes a typo in the book, FYI. _hypothesise_ should probably be _hypothesize_, right?)

**Comment by andburch** [comment]
Also, when specifying XSelect for factor-based categorical variables, does each level of the factor correspond to its own numerical index when grouping covariates in ` Xsel$covGroup`?

If I was only modelling a categorical covariate with 8 levels, would I need XSelect to be a list of 8 elements or only one?

**Comment by ovaskain** [comment]
Hi,

Yes, each level goes to its own index (but note that one level goes to baseline). Look at head(m$X) to clarify what the columns are (where I called the Hmsc-object as m). This is the design matrix created from XData and XFormula.

Best,

O2

**Comment by ovaskain** [comment]
This is a good question and we talk about quite subtle differences. I would say that the main difference is that with XSelect you assume that some covariates do not matter at all for some species / groups of species, whereas with the inclusion of traits (but not using XSelect) you assume that traits influence systematically how the covariates matter. For example, species with large body size have positive response and species with small body size have negative response is something you achieve with the traits approach but not with the XSelect approach.

O2

From: Andrew T Burchill ***@***.***>
Sent: maanantai 26. heinäkuuta 2021 17:51
To: hmsc-r/HMSC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hmsc-r/HMSC] Question about using XSelect on species subgroups or just specifying traits... (#110)


I have a dumb, conceptual question: what is the use-case of selectively applying some covariates to a subgroup of species. In reference to selecting variables only for subgroups of species:

One may hypothesise that species with different trait categories (e.g. species from different guilds) or from different taxonomical groups respond to different sets of variables.

But isn't that the whole point of having trait data? Shouldn't "guild" be included as one of the traits, and then the model will fit various responses between the different values of "guild" and different covariates? I'm curious about the differences in these two approaches and I'm wondering what I'm missing here.

(Also it looks like this quote includes a typo in the book, FYI. hypothesise should probably be hypothesize, right?)

**Comment by andburch** [comment]
Thank you!
