### ISSUE TITLE
Splitting data into training and validation sets: problems with study design matrix

### ISSUE THREAD

**Issue by gaiteiro** [hmsc-r/HMSC#113]
I would like to perform 2-fold cross-validation of a model. Unfortunately, this is a memory-hungry process and crashes my system (not enough RAM). So I am trying to do it manually....here is the code for the first fold:

```
X <- read.csv('C:/Users/smith/Documents/nnMaxEnt3/newdat549.csv', header=T)
y <- read.csv('C:/Users/smith/Documents/nnMaxEnt3/Y_all.csv', header=T)
X$ecoreg <- as.factor(X$ecoreg)
X <- X[X$ID %in% y$ID, , drop = FALSE] # leaves 313 sites present in both X and Y 
dummy <- sample(rep(0:1,each=158)) # set up random partition
dummy <- dummy[-1] # 158 + 157 = 313
X1 <- X[dummy == 0, ] # split into 2 folds
X2 <- X[dummy == 1, ]
y1 <- y[dummy == 0, ]
y2 <- y[dummy == 1, ]
absentSp <- which(colSums(y1)==0) # remove species with no presences in training set
y1a <- y1[, -absentSp]
y2a <- y2[, -absentSp] 
y1a <- y1a[, -1] # remove ID column
y2a <- y2a[, -1]
Y1 <- as.matrix(y1a) # convert to matrix Y
Y2 <- as.matrix(y2a)
library(Hmsc)
nChains = 2
thin = 5
samples = 1000
transient = 500*thin
verbose = 50*thin
# set up spatial variable
n <- nrow(X1)
studyDesign = data.frame(sample = as.factor(1:n))
xycoords <- X1[c("xcoords", "ycoords")]
rL.spatial = HmscRandomLevel(sData = xycoords)
rL.spatial = setPriors(rL.spatial,nfMin=1,nfMax=10)
# set formula and fit model
fit1 = Hmsc(Y=Y1, XData=X1, XFormula= ~ cost + fpar + lai + therm + ecoreg,
            studyDesign=studyDesign, ranLevels=list("sample"=rL.spatial), distr="probit")
fit1 = sampleMcmc(fit1, thin = thin, samples = samples, transient = transient,
                  nChains = nChains, verbose = verbose, updater=list(GammaEta=FALSE))
```

This gives me an error message "spatial distance matrix is non-metric or has duplicated points", presumably because a neighborhood matrix with only half the sites doesn't make sense? I checked for duplicated points with: `xycoords[duplicated(xycoords) | duplicated(xycoords, fromLast=TRUE),]`

But if I try to build the study design with all rows in X, I get the error "number of rows in studyDesign must be equal to number of rows in Y".

I would be grateful for any advice.

[data.zip](https://github.com/hmsc-r/HMSC/files/6930182/data.zip)

**Comment by jarioksa** [comment]
It looks to me that this is the critical line in your code:
```r
studyDesign = data.frame(sample = as.factor(1:n))
```
Here you define a study design with sample names (`1:n`) that do not exist in your spatial coordinates (see `rownames(xycoords)`. The sampling tries to pick those `xycoords` that are defined in `studyDesign`, and as these do no match, there will be missing values, and this gives the error. The error message makes wrong inference on the reason of the problem, but it is still the user error. You should use instead:
```r
studyDesign <- data.frame(sample = as.factor(rownames(X1)))
```

Please note that the row names in `X1` and `Y1` neither match. These is a potentially an issue to worry about.

**Comment by gaiteiro** [comment]
Thank you for your advice! Using rownames as sample names works.
