### ISSUE TITLE
Inconsistency in MCMC sampling when trying to achieve model convergence

### ISSUE THREAD

**Issue by cgoetsch** [hmsc-r/HMSC#118]
I have some questions/concerns about the consistency/stability of the mcmc sampling on model runs. 
 
We are running the following models that we have narrowed to 14 species and 12 environmental covariates  by testing extensive versions of smaller subsets of the data:
 
1.	NNGP spatial model with 2 additional random effects: an unstructured random effect at the sample level and a temporal random effect. 
Model specifications: Hmsc object with 7320 sampling units, 14 species, 13 covariates, 1 traits and 3 random levels 
And the model call: Hmsc(Y = Y, XFormula = XFormula.1.c, XData = X, studyDesign = studyDesign, ranLevels = list(tow = rL.tow, grid_id = rL.spatial, year = rL.time), distr = "probit")
 
2.	A non-spatial version of the same model
Hmsc object with 7320 sampling units, 14 species, 13 covariates, 1 traits and 2 random levels
Hmsc(Y = Y, XFormula = XFormula.1.c, XData = X, studyDesign = studyDesign, ranLevels = list(tow = rL.tow, year = rL.time), distr = "probit")
 
 
I have been running into 2 issues consistently in my efforts to get our models to converge.
 
1.	If I rerun a model,  using the same set.seed with the same number of chains, samples, thin and transient, etc.  the degree of convergence can vary significantly, even for models that seem to have been sampled enough to reach convergence. I don't expect that model runs with the same set.seed and mcmc sampling settings would be identical due to the mcmc algorithm; however, I also don't think that they should be as variable as I have seen, especially when one run of the model indicates that it is past the burn-in needed for adequate convergence. 
 
2.	Even when running the same model with longer burn-in or thin, sometimes the result is worse than the previous model - so, further away from convergence rather than closer.
 
For example, I thought I had the non-spatial model close to convergence. The beta parameters were adequately converged (99% < 1.1 psrf), the temporal alpha2 was converged (1.01 psrf), the omega1 parameters was converged (99% < 1.1 psrf), and the omega2 parameters for the temporal effect was almost there (only 13% < 1.1, but looking at the trace, it just appeared that we needed a longer burn-in). So, I ran a longer mcmc sampling for what I thought would be the final converged model. Yet, all of the metrics for every parameter were worse! Looking closer at the trace, I found one chain had gone off the rails after everything appeared to be converged:
 
![image](https://user-images.githubusercontent.com/83247406/131378592-14dc3b64-ee31-4d61-9852-e4ad29beed91.png)
![image](https://user-images.githubusercontent.com/83247406/131378617-46fa3d37-fa36-4d51-a09d-4f52b49a0f9e.png)

  
Across all parameters, it was consistently the third chain (green) and it consistently diverged at ~950K iterations.  Nearly every parameter was converged if we looked at the 3 "good" chains by themselves, or if we looked at the posterior sample before the green chain diverged. We thought that this meant we had reached convergence with 500K burn-in and to prevent a chain from going off the rails, we could keep that amount of burn-in and significantly lower the thin to get the 2000 samples of the posterior we want. However, after running this, many of the chains do not appear converged at all, even though they were clearly converged at the same point with the previous model run:
 
![image](https://user-images.githubusercontent.com/83247406/131378762-52ec9782-ac5c-46d6-8753-3d9fb1620b0d.png)

Also, it is not always so clear whether one chain has diverged from convergence or if it never got there in the first place. In running the spatial version of the model initially with 3 chains, 2000 samples, 200 thin and a burn-in of 400K iterations, the model seemed fairly close to convergence and appeared to need a longer burn-in.
  
Yet, when I reran the model with 4 chains, 2000 samples, 750 thin, and 750K burn-in, the convergence ended up being much worse. Looking at the parameter traces, it appeared as if the 4th chain (blue) was consistently not converging with the others. 

![image](https://user-images.githubusercontent.com/83247406/131379024-13ef1e9e-b973-4428-aaf8-2ca74872135d.png)

Looking at ess and psrf for the parameters without that chain revealed that the model was closer to convergence. However, I know that if I rerun the same model again, it may be chain 2 that doesn't converge, even if I again increase the thin and burn-in.
Should there be such inconsistency between model runs? It seems that one run will indicate that I am close to convergence, just needing more burn-in, but then the next run with more burn-in isn't any closer and sometimes is much worse. Does this indicate instability in the model? How can I get a converged model, with such extreme variation between model runs?

**Comment by FraGoblin** [comment]
Hi hi,

I have a similar issue of chains getting stuck in a local mode. How did you manage to solve this?

Thanks,
Francesco
