### ISSUE TITLE
Slow mixing for Poisson counts

### ISSUE THREAD

**Issue by mr742** [hmsc-r/HMSC#12]
Hello,

We are encountering some difficulties when modelling Poisson counts with the most recent version of the Hmsc package (https://github.com/hmsc-r/HMSC). Our data consist of highly overdispersed counts for 113 species in 2603 sites. The model includes 7 covariates and 3 random effects.

We are running a single MCMC chain, which shows poor mixing and takes a long time (several days) to complete the specified number of iterations (50K including 25K burn-in).

For comparison, we ran the same model using the earlier version of the package (HMSC; https://github.com/guiblanchet/HMSC), and the same data used in Hmsc. The resulting chains show better mixing and run considerably faster (see accompanying figure below). The figure shows output for species 113 only, but the same pattern holds for most other species as well.

We are wondering whether the default settings (e.g., for priors, or for proposal variances) in Hmsc are hindering its performance.

We would appreciate any suggestions on how to improve the mixing of our chain.

Our model specification is:

thin = 25
samples = 1000
nChains = 1
transient = samples*thin

hmsc_mod = Hmsc(Y=Y, X=X, XFormula =XFormula, C=C, distr="poisson", studyDesign=studyDesign, ranLevels=ranlevels)

hmsc_out = sampleMcmc(hmsc_mod, samples=samples, thin=thin, transient=transient, nChains=nChains, nParallel=nChains)

The inputs are:

\> str(Y)
 int [1:2603, 1:113] 1 1 3 2 1 1 3 3 2 1 ...
 \- attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:113] "y1" "y2" "y3" "y4" ...

\> str(X)
 num [1:2603, 1:7] -0.559 -0.825 0.213 0.449 1.097 ...
 \- attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:7] "x1" "x2" "x3" "x4" ...

\> XFormula
~x1 + x2 + x3 + x4 + x5 + x6 + x7

\> str(C)
 num [1:113, 1:113] 1 0 0 0 0 0 0 0 0 0 ...
 \- attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : NULL

\> str(studyDesign)
'data.frame':	2603 obs. of  3 variables:
 $ re1: Factor w/ 10 levels "A","B","C",..: 6 6 1 1 1 1 1 1 1 1 ...
 $ re2: Factor w/ 2123 levels "s1","s2",..: 227 230 39 38 60 48 46 1 19 6 ...
 $ re3: Factor w/ 11 levels "year1","year2",..: 10 10 7 7 7 7 7 7 7 7 ...

![output_HMSCvsHmsc](https://user-images.githubusercontent.com/13107254/61417035-c9d85d80-a8c3-11e9-9af6-772a645600f2.png)

**Comment by gtikhonov** [comment]
Hello @mr742 

1) There is a considerable difference in the implementation of samplers for Poisson data distributions in `HSMC` and `Hmsc`. E.g. if you carefully check the function that is the cornerstone for handling Poisson observations in HMSC [(link)](https://github.com/guiblanchet/HMSC/blob/master/src/sampleYlatentPoisson.cpp), you can figure out that it does not sample from the true conditional posterior for the Poisson observational model. Instead, it samples from the conditional for somewhat "int-truncated some-link-function-adjusted latent Gaussian model".  While this approach is alright and has been used in other modelling frameworks previously, it does not handle the assumptions behind the Poisson distribution. Our current implementation in Hmsc seeks to provide a principally correct solution to this problem, approaching the Poisson observation model as a limit of lognormal and Gamma overdispersed-Poisson [(this article gives the theoretical foundations)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4180062/).
2) Given the above-mentioned way of obtaining Poisson observation model as a limit and the fact that you consider your data "highly overdispersed", you may want to apply `"lognormal poisson"` observation model in the place of `"poisson"`. That model allows for some extra flexibility in the sampling scheme and in our experiments we found that typically that model had better mixing properties.
3) The very this problem of slow mixing (especially with Poisson observational model) is one of the key directions of our scientific investigation at this moment.

**Comment by mr742** [comment]
Hello @gtikhonov,

Thanks for your informative answer. We will try your suggestion to use the lognormal Poisson.
