### ISSUE TITLE
Error in predict function: Error in seq.default(start, length(chain), thin): wrong sign in 'by' argument

### ISSUE THREAD

**Issue by janinepdasilva** [hmsc-r/HMSC#125]
I have been working with the Hmsc package for joint modelling of freshwater fishes and mussels communities. Everything went really well during model building but I am experiencing some trouble now that I am trying to make predictions.

I've built two models as follows:

xy <- as.matrix(cbind(data$Long, data$Lat))

colnames(xy) <- c("c-coordinate", "y-coordinate")
rownames(xy)=data$HYBAS_ID

# To define a spatial random effect, we need to include the Basin ID (HYBAS_ID) in the studyDesign

studyDesign <- data.frame(as.factor(data$HYBAS_ID))
colnames(studyDesign) <- c("HYBAS_ID")
#studyDesign = data.frame(sample = as.factor(1:164))
#Define the random level object. As we wish to define a spatial random effect, use the sData argument

rL <- HmscRandomLevel(sData = xy)

nChains = 2
nParallel = 2 # optional setting of nParallel
thin = 10 # Run 1, 10, 100 to achieve model convergence
samples = 1500*thin
transient = 500*thin

XFormula = ~ ele_mt_sav + sgr_dk_sav + ORDER_ + hft_ix_u09 + bio1 + bio18 + up_S_CaCO3 + continentality

m.FULL = Hmsc(Y = YData, XData = XData, XFormula = XFormula,
              distr = "probit",
              studyDesign = studyDesign,
              ranLevels = list(HYBAS_ID=rL))

m.SPACE = Hmsc(Y = YData, XData = XData, XFormula = ~1,
               distr = "probit",
               studyDesign = studyDesign,
               ranLevels = list(HYBAS_ID= rL))

models <- list(m.FULL, m.SPACE)
  for (i in 1:2) {
    models[[i]] = sampleMcmc(models[[i]], thin = thin, samples = samples, transient = transient, nChains = nChains)
   
  }

Then I try to predict using the m.FULL model, for example:

Gradient <- constructGradient(hM = m.FULL, focalVariable = "bio1")
predY <- predict(m.FULL, Gradient = Gradient)

And I get the following error:
Error in seq.default(start, length(chain), thin) : 
  wrong sign in 'by' argument

I have already tried to play with the nChains, thin, sample and trasient values, but everytime I get the same error.

Can someone please help me with this?

**Comment by jarioksa** [comment]
I have no data to verify this, but this is my guess: your `m.FULL` has no samples. You have defined a non-sampled `m.FULL` but then your usage is this:
```r
models <- list(m.FULL, m.SPACE)
for (i in 1:2) {
models[[i]] = sampleMcmc(models[[i]], thin = thin, samples = samples, transient = transient, nChains = nChains)
}
```
After this, `models[[1]]` has posterior samples, but the original `m.FULL` is untouched and has no samples. Hence you get an error. Either of these should do:
```r
m.FULL <- models[[1]]
predY <- predict(m.FULL, Gradient=Gradient)
## alternatively
predY <- predict(models[[1]], Gradient=Gradient)
```
Obviously we need to add a check against predicting with unsampled models.

**Comment by janinepdasilva** [comment]
Thank you so much for your answer. Did I not define a sampled m.FULL by using the following:
`thin = 1 # Run 1, 10, 100 to achieve model convergence
samples = 1500*thin
transient = 500*thin`

**Comment by jarioksa** [comment]
@janinepdasilva no, you did nothing to your `m.FULL`, but all your samples were saved in a list of `models`. The first element of this list `models[[1]]` was a copy of `m.FULL`, but samples were only added to this copy `models[[1]]`, and the original `m.FULL` was untouched.

**Comment by janinepdasilva** [comment]
Solved. Thank you
