### ISSUE TITLE
Unable to set non-zero-centered Gamma priors plus a few minor fixes

### ISSUE THREAD

**Issue by AdamMS** [hmsc-r/HMSC#13]
I have been experimenting with the Hmsc package for about a month now, and I really appreciate the package.  Thank you for all the hard work you've put into it.

I have one issue that feels important and three that seem very minor.  I hope it's okay that I am presenting them all in a single issue (let me know if I should have divided them up).  I am attaching an MWE that illustrates all of them.

(1) Setting a prior on gamma that is not zero-centered.

Following up on a post from Issue #10, I tried to use priors to force Hmsc to treat a column of the X matrix as an offset, and I think Hmsc is implementing it incorrectly (or I am implementing Hmsc incorrectly).

If the offset (i.e. log(effort)) is column K of the X matrix, then my goal is to have Beta_{jK} ~ N(1,0) for all species j=1,...,J.  To make this happen in the Hmsc framework, we require a prior on Gamma_{1K} ~ N(1,0), and we also need V[K,K] to be nearly zero.

However, my output (traceplot) behaves as though I have: (a) set a Gamma_{1K} ~ N(0,0) prior while (b) set an initial value for MCMC sampling of 1 for Gamma_{1K}.  In other words, my effort to set mGamma=1 is being interpreted as changing the initial value instead of the prior mean.

In my attached toy example, the Trait matrix is just an intercept column, and K is the last column of X, so the code that makes sense to me (for a model setup called 'm.setup') is:
```
m.setup <- setPriors(m.setup,
                     V0 = diag(c(rep(1, K-1), 1e-8)),
                     f0 = K+1,
                     mGamma = c(rep(0, K-1), 1),
                     UGamma = diag(c(rep(1, K-1), 1e-8))
)
```

(2) Labels for Eta.

Assume I have a random effect with R = 5 levels that I defined using HmscRandomLevel() and named 'rL'.  The column names for Eta appear to be set using the first R values of rL -- rL$pi[1:R] -- instead of using the the random effect levels -- levels(rL$pi)[1:R].

So, for example, if the levels of my random effect are: A, A, B, B, C, C, D, D, E, E, the model fit object has labels A, A, B, B, C instead of A, B, C, D, E.

(3) Labels for Lambda

When I extract a posterior sample of the Lambda matrix for a random effect, the variable names correspond to building a matrix with byrow=TRUE, but the values in the vector correspond to building a matrix with byrow=FALSE.  This is easier to explain in the attached MWE than verbally.

(4) Error for adaptNf > transient

I should know better than to accidentally set adaptNf > transient when defining my sampleMcmc(), but that hasn't prevented me from doing so.  It would be nice to add an error warning for the user to highlight this mistake.
[MWE non-zero priors.txt](https://github.com/hmsc-r/HMSC/files/3412638/MWE.non-zero.priors.txt)

**Comment by gtikhonov** [comment]
I've had a quick look at the implementations for Gamma conditional samplers. Indeed, it seems there is at least one place, where at some change in the past the sampler implicitly started assuming that the `mGamma` is a vector of zeros. I will have a more thoughtful examination of this bug and come back once I fix it (in next couple days).

**Comment by gtikhonov** [comment]
Hello! Thanks again for the extended feedback and the MWE that you've posted.
I have now addressed all the issues that you've raised and fixed the associated bugs in the codes. The MWE produces no inconsistencies, but if you face some other suspicious behaviour, please let us know.

**Comment by AdamMS** [comment]
Great!  Thank you so much, @gtikhonov.  I will download the updates and see how it goes.  I do not expect to find any inconsistencies outside the MWE, but I'll let you know if I do.
