### ISSUE TITLE
Error with computePredictedValues function due to R/Rstudio settings

### ISSUE THREAD

**Issue by cgoetsch** [hmsc-r/HMSC#131]
I'm getting an error with the function computePredictedValues that appears to be related to something with the R/Rstudio set up rather than something with the function itself.

Here is the line of code I am having issues with 
cvpreds = computePredictedValues(m, partition = partition, updater=list(GammaEta=FALSE), nParallel = nParallel)
    
I have been running various HMSC analyses on two separate computers to speed project completion. The above line of code works fine on one computer but fails with the following error on the other:

Error in terms.formula(formula, data = data) : 
  '.' in formula and no 'data' argument

Here is the traceback:
6: terms.formula(formula, data = data)
5: terms(formula, data = data)
4: model.frame.default(XFormula)
3: model.frame(XFormula)
2: Hmsc(Y = hM$Y[train, , drop = FALSE], X = XTrain, XRRR = XRRRTrain, 
       ncRRR = hM$ncRRR, XSelect = hM$XSelect, distr = hM$distr, 
       studyDesign = dfPi, Tr = hM$Tr, C = hM$C, ranLevels = hM$rL)
1: computePredictedValues(m, partition = partition, updater = list(GammaEta = FALSE), 
       nParallel = nParallel)

I thought at first that it may be a problem with the version of HMSC. But both computers are updated with the latest version installed from github. Then, I thought it may be due to the version of R. The computer generating the error was running the latest version of R 4.1.2 and the computer running the code with no problems was running an older R version (4.0.2). So I switched the version on the error computer to the earlier version and reinstalled all the relevant packages. But I am still getting the error. The only thing I can think of is that there is an inconsistency with the version of one of the other R packages needed for this function or an inconsistency with one of the other Rstudio settings (both computers are running the same version of Rstudio). 

Have any of the developers run into this problem before? I can send a list of the packages (with version) that are installed on R from both computers, but I have come to the limit of my personal troubleshooting skills. I'd appreciate any help trying to figure out why one computer is erroring out on code that runs fine on another.

Thanks in advance!
Chandra

**Comment by jarioksa** [comment]
This is a regression caused by commit b47e8861b5c488967afc1a5eef8a2e9c1fdd7dfb. I'll revert that.

**Comment by jarioksa** [comment]
Current master should be OK in github.

**Comment by cgoetsch** [comment]
Thanks, Jari. Everything is working fine now.
