### ISSUE TITLE
Memory leak when performing NNGP

### ISSUE THREAD

**Issue by jonpeake** [hmsc-r/HMSC#154]
I have a fairly large spatial dataset that explodes in RAM when I try to run a spatial NNGP HMSC model. The issue appears to come from the following fewlines of code in `updateEta`:
```
R = Matrix::chol(iUEta)
tmp2 = backsolve(R, as.vector(t(fS)), transpose = TRUE) + 
             rnorm(nf * np[r])
feta = backsolve(R, tmp2)
```
When I run these lines in a debugging environment, the `backsolve` calls try to create a large vector that overwhelms the available RAM. While this may be some sort of bug in the Matrix or SparseM packages, I've seemed to have stumbled upon a solution/workaround.

When I use `solve` on `t(R)` instead of `backsolve` with `transpose = TRUE` on the simulated dataset from the spatial vignette, I get identical results for Eta. This also prevents the function from attempting to allocate a large non-sparse vector and thus eating up RAM. Is there any chance that an update could be pushed to the repo that includes this modification? I'm happy to create a fork that addresses this for my needs, but others may be having similar issues.

**Comment by gtikhonov** [comment]
I am pretty sure that I have tested these lines for this very matter and my conclusion was different at that point. However, I fully comprehend that my conclusion could have been erroneous or something have changed with the involved packages. It seems absolutely reasonable to rework this piece of code with `solve()` from `Matrix` package, but we shall ensure that the proper variant among the implemented variety is used. Namely, the one that is designed to deal with triangular sparse matrices as the first argument. If you can draft a proper replacement, I would gladly push it to the master quickly.
