### ISSUE TITLE
Percentage cover modelling

### ISSUE THREAD

**Issue by charleygros** [hmsc-r/HMSC#159]
Hi there,

I have a dataset where the biological data is expressed in percentage cover (ie species X is covering 43% of the seafloor).

What HMSC approach do you recommend?

My understanding is that the `probit` is suited for Presence-Absnce.
And the other distribution are not bounded.
Whereas my data is bounded between 0 and 100.

Many thanks in advance
Charley

**Comment by charleygros** [comment]
Thanks @ovaskain, that's helpful.

`hist(Y.abuc)` looks nicely as a normal distribution, so I'm trying this now.

Two more questions on Hurdle model if that's ok:
1. To get the final prediction, do you recommend multiplying `E.pa` and `E.abuc`? Or do you recommend binarizing `E.pa` first before multiplying it to `E.abuc`?
2. How do you estimate the uncertainty of a hurdle model? `model.pa` has its `CI5.pa` and `CI95.pa`.. same for `model.abuc`.. I wonder what would be the best way to estimate the uncertainty of `model.hurdle`.

Many thanks in advance.

**Comment by ovaskain** [comment]
Hi,

  1.  To get the final prediction, do you recommend multiplying E.pa and E.abuc? Or do you recommend binarizing E.pa first before multiplying it to E.abuc?
As predicted abundances often have a long tail of high values, I would recommend computing posterior median. Thus predicting actual data rather than expected values (0/1 * count) for each posterior sample and then taking median from the posterior predictive distribution.

  1.  How do you estimate the uncertainty of a hurdle model? model.pa has its CI5.pa and CI95.pa.. same for model.abuc.. I wonder what would be the best way to estimate the uncertainty of model.hurdle.
By the credible intervals of the above-mentioned posterior predictive distribution.

O2

**Comment by charleygros** [comment]
Thank you @ovaskain !

Wondering if you could confirm that I understood correctly: you are suggesting an approach with only one abundance model (ie no use of `model.pa`), something like:

```
# Get training data
Y.abuc = Y
Y.abuc[Y==0] = NA
Y.abuc = scale(log(Y.abuc)) 

# Fit the model
model.abuc = Hmsc(Y.abuc, dist='normal', ...)

# Prediction time / extrapolation
Pred.abuc = predict(model.abuc, Gradient=gradient, expected = TRUE)

Pred.abuc = as.data.frame(apply(simplify2array(Pred.abuc), 1:2, median))
Pred  = exp(predY_E * sd_abuc) + mean_abuc)
```

... and use the resulting `Pred` to map the predicted percentage cover.

Am I missing something?

Many thanks in advance
Charley

**Comment by ovaskain** [comment]
No, I propose that you use a hurdle model, so a combination of Y.pa and Y.abuc. This is because Y.abuc (as you defined it below) is not model of abundance, but of abundance conditional on presence. Hence you need a separate model for presence, i.e. the model Y.pa.

O2

**Comment by charleygros** [comment]
> No, I propose that you use a hurdle model, so a combination of Y.pa and Y.abuc. This is because Y.abuc (as you defined it below) is not model of abundance, but of abundance conditional on presence. Hence you need a separate model for presence, i.e. the model Y.pa.

That makes more sense. Thanks Otso. Really appreciated.
So, now, I'm not clear about how to combine the predictions of the two models, `model.pa` and `model.abuc`, to have an estimate of the percentage cover / abundance.

How would you recommend to combine them?
Can you simply multiply the model predictions? Something like below?

```
# Get training data
Y.pa = 1*(Y>0)
Y.abuc = Y
Y.abuc[Y==0] = NA
Y.abuc = scale(log(Y.abuc)) 

# Fit the models
model.pa = Hmsc(Y.pa, dist='probit', ...)
model.abuc = Hmsc(Y.abuc, dist='normal', ...)

# Prediction time / extrapolation
Pred.pa = predict(model.pa, Gradient=gradient, expected = TRUE)
Pred.pa = as.data.frame(apply(simplify2array(Pred.pa), 1:2, mean)) 

Pred.abuc = predict(model.abuc, Gradient=gradient, expected = TRUE)
Pred.abuc = as.data.frame(apply(simplify2array(Pred.abuc), 1:2, median))
Pred.abuc = exp(predY_E * sd_abuc) + mean_abuc)

# Combine the predictions
Pred  = Pred.pa * Pred.abuc
```

Many thanks Otso!

Charley

**Comment by brendanf** [comment]
I think Otso was suggesting that you should multiply the PA predictions by the conditional abundance predictions *before* taking the median.

**Comment by ovaskain** [comment]
Indeed!

O2

**Comment by charleygros** [comment]
> I think Otso was suggesting that you should multiply the PA predictions by the conditional abundance predictions _before_ taking the median.

Fantastic! Thanks @brendanf, Thanks @ovaskain. Understood. Appreciate your help
