### ISSUE TITLE
can't fix the number of latent factor

### ISSUE THREAD

**Issue by guercha** [hmsc-r/HMSC#16]
Hi, 

I am trying to compare the HMSC model for different number of latent factors. I compute the models by fixing the number of latent factor. The performance of the models increase with 0, 1 and 2 latent factors but when I am trying to run an Hmsc model with 3 or more latent factors, I don't see any difference with the Hmsc model with only 2 latent factors (I suppose it's the optimal number of latent factors to avoid modeling noise). I compare the models with AUC and R2 of Tjur. 

Here is my code : 

thin = 30
samples = 1000
transient = 10000
verbose=500*thin
nbChains = 2

sample.id=1:761
sample.id = as.factor(sample.id)
studyDesign = data.frame(sample=sample.id)

rL = HmscRandomLevel(units = studyDesign$sample)

rL$nfMax=3
rL$nfMin = 3

model = Hmsc(Y = ydata, XFormula = ~., 
              XData = xdata, distr = "probit", 
              studyDesign = studyDesign, ranLevels = list("sample"=rL))

res_HMSC = sampleMcmc(model, samples=samples, 
                                 transient = transient, thin = thin, 
                                 verbose = verbose,
                                 nChains = nbChains,
                                 adaptNf = rep(0, model$nr))

Can anybody helps me ?

**Comment by oysteiop** [comment]
Hi, it seems you have set 'adaptNf' to 0 in sampleMcmc, hence the number of factors is now updated. Try setting e.g. adaptNf =transient

Cheers,
Öystein

**Comment by guercha** [comment]
Thanks for your help !
I tried your code but I have the same result...

**Comment by guercha** [comment]
Thanks for your answer !
I tried your code but it doesn't change the result...
Maybe I was not enough clear in my question, sorry for that. 
My question is : How can I fix the number of latent variable used in the model ?

**Comment by oysteiop** [comment]
Hi, in principle your approach should work, i.e. setting nfMax = nfMin. By results not changing, do you mean than e.g. r2 and AUC does not change, or is the number of latent factors unchanged (you can use e.g. getPostEstimate() to look at the posterior means of e.g. the Lambda parameters to see how many latent factors were included). If former, it's possible that model performance is similar with different numbers of altent factors. If latter, something else could be wrong.

Öystein

**Comment by hmsc-r** [comment]
In hmsc, the parameters of the shrinkage prior for the latent variables has a large effect (and can be more important prior choice than the number of factors, which theoretically is infinite). If there is a lot of increase with shrinkage with increasing factor id (a2 large, say a2=50), then only the first 1-2 factors typically have an effect (of  course, depending on the data). Thus, it may be that the 3rd factor is so small that it does not show any effect.

**Comment by guercha** [comment]
Hi !

I check the getPostEstimate() results and everything is OK : the number of latent factors is the same as in nfMax = nfMin, so the number of latent factors changes. 

The performances of the R2 and AUC don't change, and that's what I find strange : when I try with a similar package e.g BORAL, those performances increase when I add a latent factor, which is not the case here : the performances remain the same. 
I don't understand why, I mean when I add a latent factor I should improve my model because I take into account a supplementary part that is not explain by the measured covariates or the other latent factors...
Maybe my reasoning is not good ?

Thanks for your help,

Charlotte

**Comment by guercha** [comment]
Hi Hmsc-r,

I did not think about that ! 
This should be the reason why I have those results, boral doesn't use the same prior ! I will pay attention to that !

Thanks all for your help !

Charlotte

**Comment by gtikhonov** [comment]
> I don't understand why, I mean when I add a latent factor I should improve my model because I take into account a supplementary part that is not explain by the measured covariates or the other latent factors...

Well, this depends on how do you measure the quality of your model. If you consider some type of **explanatory** power measure, so how the model suits/explains the data it was fitted to, then this statement is generally true. This is because the model with additional factor is more flexible and unless you introduce some penalisation for this extra flexibility in your quality measure, you should get better results. Some exceptions possible if the more flexible model is so complex that you cannot reliably fit it with the computational resources that you allocated to that (e.g. MCMC length). 

However, the fact that the model is better capable of explaining the seen data, does not mean that the model is better for explaining the phenomenon in general. One common problem is **overfitting**, when your model starts capturing noise as a meaningful pattern. To avoid this, the model be tested with some **predictive** performance measures, e.g. using a **validation** dataset that was not used for training.
