### ISSUE TITLE
In cor(lbeta[[i]][k, ], lmu[[i]][k, ]) : the standard deviation is zero

### ISSUE THREAD

**Issue by LafontRapnouilTristan** [hmsc-r/HMSC#186]
Hello,

thank you for the amazing work regarding Hmsc!

I am currently trying to build a spatial model with no traits.

I noticed that when building the model a "dummy" trait (full of '1') is created and when running` summary(mymodel)` I indeed see that it has one trait.

 Everything runs fine but when using `computeVariancePartitioning` I have the following warnings:

> In cor(lbeta[[i]][k, ], lmu[[i]][k, ]) : the standard deviation is zero

Investigating the objects I indeed find that all my values for `lmu[[i]][k, ]` are similar. If I understood Mu is the parameter linking traits and sp niches. Am I right to consider this warning irrelevant as, having no traits, it is normal to have meaningless Mu parameter?

Thank for you work and time. 
I can provide you more information about my model If the issue proves to no be as trivial as I thought!

**Comment by ovaskain** [comment]
Even if there are no traits, Hmsc still estimates community-level parameters mu and V, which then model the mean (mu) and variance-covariance (V) in species responses to environmental predictors (beta). This is done by having intercept-only model for traits. So everything seems ok with your model, you can ignore the warning (that part of variance partitioning is not meaningful if there are no traits).

O2

From: Lafont Rapnouil Tristan ***@***.***>
Sent: perjantai 3. toukokuuta 2024 11:40
To: hmsc-r/HMSC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hmsc-r/HMSC] In cor(lbeta[[i]][k, ], lmu[[i]][k, ]) : the standard deviation is zero (Issue #186)


Hello,

thank you for the amazing work regarding Hmsc!

I am currently trying to build a spatial model with no traits.

I noticed that when building the model a "dummy" trait (full of '1') is created and when running summary(mymodel) I indeed see that it has one trait.

Everything runs fine but when using computeVariancePartitioning I have the following warnings:

In cor(lbeta[[i]][k, ], lmu[[i]][k, ]) : the standard deviation is zero

Investigating the objects I indeed find that all my values for lmu[[i]][k, ] are similar. If I understood Mu is the parameter linking traits and sp niches. Am I right to consider this warning irrelevant as, having no traits, it is normal to have meaningless Mu parameter?

Thank for you work and time.
I can provide you more information about my model If the issue proves to no be as trivial as I thought!

**Comment by LafontRapnouilTristan** [comment]
Hello,

Thank you very much for this quick response.
Bests.
