### ISSUE TITLE
sampleMCMC() error on cluster

### ISSUE THREAD

**Issue by rburner** [hmsc-r/HMSC#26]
Hi - I mentioned this issue to Otso and he suggested I post here.

When I run the following code on an HPC cluster (with any value for nParallel) I get the error shown in the image:

>sixmodelsHPC[[1]]
Hmsc object with 999 sampling units, 334 species, 6 covariates, 6 traits and 3 random levels

>sixmodelsHPC[[1]] = sampleMcmc(sixmodelsHPC[[1]], thin = thin, samples = samples, 
                          transient = transient, nChains = nChains, nParallel = 1, 
                          verbose = verbose, initPar = "fixed effects")

<img width="433" alt="ERROR" src="https://user-images.githubusercontent.com/36172156/65990934-d1ec7600-e48c-11e9-91de-46cf96b753ef.png">

The same code, with the same model objects, runs fine on my PC (with an Hmsc installation from August; Hmsc installation date on the HPC cluster was today.

Secondarily, is it true that I can't use more cores than the number of chains (as per the warning)?

Thanks!

Ryan

**Comment by gtikhonov** [comment]
@RBurn thanks for posting the problem here - it is always better than to post one of the developers directly, since then any of us can provide some insight.
Based on the error message, I would guess that this is a bug introduced in some commit that was made after August, most likely a one related to implementing several ways to handle large spatial data in Hmsc. @MelindadeJonge , since you were primarily developing that part, could you please have a look at this?

**Comment by RBurn** [comment]
@gtikhonov thanks for the quick response. I can confirm that when I eliminate the spatial (site) random level the model starts running successfully on the recent Hmsc installation. 

But, when I set nParallel to anything other than 1 (either on my PC or on the HPC, whether with 1 or 2 nodes) the model never starts running iterations (verbose = 1) - it just sits there thinking.

**Comment by gtikhonov** [comment]
Have you tried to run some very short chains? Once nParallel > 1 the code starts multithreading and produces no output before the threads are completed.

**Comment by rburner** [comment]
@gtikhonov Ah, of course, thank you for that! When I run short strings it works and I've done some tests.

When nParallel = nChains the overall speed is proportionally faster! But, increasing NParallel beyond that doesn't have any effect on speed. 

Also, no speed change when using multiple nodes (I guess the 'parallelization' can only use 1 thread on one node per chain?)

**Comment by gtikhonov** [comment]
Please have a look at the issue #23 - it seems that there is actually quite a variety of how the combination of internal linear algebra routines parallelisation and chain-wise parallelisation work depending some not-so-clear yet characteristics of you computational environment.

**Comment by MelindadeJonge** [comment]
@rburner can you show me how you set the random levels that led to the error message in your initial post?

**Comment by rburner** [comment]
> Please have a look at the issue #23 - it seems that there is actually quite a variety of how the combination of internal linear algebra routines parallelisation and chain-wise parallelisation work depending some not-so-clear yet characteristics of you computational environment.

@gtikhonov Thanks, yes, seems like it will take some time to get to the bottom of the that one.

**Comment by rburner** [comment]
> @rburner can you show me how you set the random levels that led to the error message in your initial post?

@MelindadeJonge Yes - here is the code:

This code works fine on my PC (but not on the cluster). This may be an unrelate problem, but I don't think the current code gets the spatial random effect working when I have multiple years for the same sites (as in these data) – I get flat ‘0’ traces of Alpha1 even when I simulate spatial data with a strong effect.
 
I can make the spatial effect work when I have only one year/visit per site (i.e. when nrows(xycoords) = nrows(Y) = …etc), so my only guess is that the problem relates to row names or the studydesign dataframe setup to make the correct rows in the Y matrix correspond to the appropriate row in the xycoords matrix. I’m not entirely clear on when row/column names are significant and when they aren’t.
 
Can you see an obvious error in my current setup? Basically each row in the Y and XData corresponds to one site_year combination. But then in my xycoords file I only have one row for each site.
 
Thanks,
Ryan
 
`> 
> XData[1:5,1:5]
  Age HardVol SpruVol MinAge State
1  61      13     212     39   Man
2  42      31     111     18   Man
3  58      25      88     22   Man
4  61      13     212     39   Man
5  21      30      35      4   Man
> 
> head(studyDesign)
        Site Year Proj
1 s199800001 1998 Dr.S
2 s199800002 1998 Dr.S
3 s199800003 1998 Dr.S
4 s199800004 1998 Dr.S
5 s199800005 1998 Dr.S
6 s199800006 1998 Dr.S
> 
> head(xycoords)
               [,1]     [,2]
s199800001 10.99343 59.85742
s199800002 10.98626 59.85786
s199800003 10.98885 59.85753
s199800004 10.98762 59.85662
s199800005 10.99523 59.84270
s199800006 10.98763 59.84090
> 
> rL1 = HmscRandomLevel(sData = xycoords) 
> rL2 = HmscRandomLevel(units = studyDesign$Year)
> rL3 = HmscRandomLevel(units = studyDesign$Proj)  ##project random level is important!!!!
> 
> ###probit models
> #define 'hab' model
> m1 = Hmsc(Y=Ypres, XData=XData, XFormula=~Age + HardVol + SpruVol + State + Effort, TrData = TrData, TrFormula = ~host_tree + guild + wingload, + phyloTree = phy, studyDesign=studyDesign, ranLevels=list("Site"=rL1, "Year"=rL2, "Proj"=rL3), distr = "probit")`

**Comment by MelindadeJonge** [comment]
Strange, I don't see any obvious issues with your setup. Indeed, the rownames of xycoords need to be the names of the sites, which seems fine. And when I recreate your model with some simulated data I get neither an error message nor a flat Alpha posterior. So I'm afraid I cannot give you a straight answer yet. 

I have a few additional question:
1. The model you were running on your cluster, are you sure you specified rL1 using sData (as is needed for coordinates) and not using distMat? I found a bug that returns the error you gave when using distMat, but not when using sData. 
2. Are the columns in your studyDesign stored as factors?

**Comment by gtikhonov** [comment]
> I can make the spatial effect work when I have only one year/visit per site (i.e. when nrows(xycoords) = nrows(Y) = …etc) ...

Can you please tell a bit more of what are the different settings you've tried. The names of the spatial locations are a quite unclear to me. As I understood it so far:
1) in the former case you have multiple observations from the same coordinate for each spatial location, which means that you have multiple appearances of e.g. `s199800001` in `StudyDesign$Site`, which would correspond to several observations at a single site in different years.
2) in later case there is one-to-one correspondence between rows of Y and xycoords.

If my vision matches what it is in fact, then I can come up with scenario once you get estimates of zero spatial correlation in the first case and non-zero spatial correlation in the second. Imagine that your data are spatially correlated within each year, but are completely independent across the years. Then your model that has an additive space and time effects would not be capable to capture that properly, since roughly speaking, it assumes that there is some single common spatial field that is shifted higher or lower in different years. However, if you subset the data to a single year, then it would properly identify the spatial signal.

Depending on what are you modelling aims, you may consider to additionally add a random effect corresponding to the interaction between year and space - then you would effective try to decompose the spate-temporal structure into a) common spatial pattern, b) common temporal pattern and c) idyosincratic spatio-tempoal effect.

**Comment by rburner** [comment]
@gtikhonov  @MelindadeJonge  
Thanks for your continued help! Yes, the situation is as @gtikhonov interpreted it. In the 'case 1' example I have several years for each site (so, rows in the Y matrix correspond to site_year combinations (e.g. s199800001_2015), each of which has its own row in study design but not in xycoords, where each site only has single row (named the same as the sites). 

I confirmed that I did use 'sdata = xycoords' in setting the random level, and that columns are set as factors in studyDesign. 

I think I understand the point of @gtikhonov, that a given dataset might have correlations within years but not across years, resulting in a non-significant estimate of spatial effect. But, my simulation had a consistent spatial effect between years. And am I correct in thinking that even with no spatial signal the Alpha posterior trace should show some minor variation rather than having exactly a zero value each time? That was the main thing that convinced me I didn't have it setup properly. Maybe I have some subtle issue in names matching or something...I can try some more examples but am traveling the next few days.

**Comment by MelindadeJonge** [comment]
Hi Ryan, 

Unfortunately I have not been able to reproduce the problems you mention yet. Could you perhaps post the code you used for the simulated data that gave you the issues?

**Comment by rburner** [comment]
Hi Melinda,

Ok, I will upload some code, thank you. I'm on holiday traveling this coming week so it may not be til the following week unfortunately.

Thank you,

Ryan


Sent from my mobile device


-------- Original message --------

**Comment by rburner** [comment]
Hi All,

I just wanted to respond one more time to this issue - after some time in Helsinki I'm not having the above error message any more (though I don't know exactly when/why it disappeared and I can't recreate it.

For people in the future reading this post, there was at least one (maybe unrelated) problem with my code above - when I set up the random levels for 'year' and 'project' it should have been as follows to include only unique levels of each factor:

rL2 = HmscRandomLevel(units = levels(studyDesign$Year))
rL3 = HmscRandomLevel(units = levels(studyDesign$Proj))

Thanks for all the help!
