### ISSUE TITLE
Hmsc::computePredictedValues - Error in Eta[[r]]

### ISSUE THREAD

**Issue by clementviolet** [hmsc-r/HMSC#43]
Hi everyone! 

Thanks for the package! I've got an error when I try to use the function `Hmsc::computePredictedValues`. I've got the following error message `Error in Eta[[r]][as.character(dfPiNew[, r]), ]: no dinames attribute for array`.

So I dig a bit onto your code, and in fact the problem come from the `HMSC:::predict.Hmsc()`. At a moment, it called the function `Hmsc::predictLatentFactor` to compute `predPostEta[[r]]` which is in turn used to compute `Eta[[r]]`. `Hmsc::predictLatentFactor`returns returns a list of array of dim `0x5`.

I don't know if the issue is caused by my model specification, or by the package itself. So I will show you how I had constructed my model.

So here are my model specs : `Y`is a matrix of 172x92 matrix, `X` is 172x92 data frame and the `sampling_design` is a data frame of 172x1 samples id. 

Here is the heart of the code :
```
rL <- HmscRandomLevel(units = sampling_design$sample)

model <- Hmsc(Y = as.matrix(Y), XData = as.data.frame(X),
              XFormula = ~ .,
              distr = "lognormal poisson",
              studyDesign = sampling_design,
              ranLevels = list(sample   = rL))

thin      <- 100

samples   <- 1000
transient <- ceiling(0.5 * thin * samples)
nChains   <- 4

hmsc_samp <- sampleMcmc(model,
                   samples = samples,
                   thin = thin,
                   transient = transient,
                   nChains = nChains,
                   nParallel = 1,
                   verbose = 1
)
```

I hope you find the solution to my problem. 

Regards,

Clément.

**Comment by ovaskain** [comment]
Sounds like some formatting problem.

 >So here are my model specs : |Y|is a matrix of 172x92 matrix

Sounds good: 172 sampling units and 92 species. I assume all values in Y 
are non-negative integers as you apply the lognormal Poisson model.

 > |X| is 172x92 data frame

Do you really have 92 covariates?

 >and the |sampling_design| is a data frame of 172x1 samples id.

Nothing wrong with this, but let me note that random effect at sampling 
unit level is optional to include (rather than "forced by study 
design"), and it should be included only if you are interested in 
co-occurrence patterns at that level.

> Here is the heart of the code :
>
> |rL <- HmscRandomLevel(units = sampling_design$sample)|

|Here sample should be factor; if not, that can cause a problem.|

|The rest of the code looks good. But most often the problem is with 
formatting the input matrices. If you can't fix this, send reproducible 
code that I can run and see the error (e.g. to me by email) so I can 
figure out what is the issue.|

Otso

**Comment by clementviolet** [comment]
Hi!

I would like to thank you for your quick answer. 

> Sounds good: 172 sampling units and 92 species. I assume all values in Y are non-negative integers as you apply the lognormal Poisson model.

Yes they're all abundance data and each column is a specie.

> Do you really have 92 covariates?

Sorry, I've made a mistake, I've only 20 environmental variables.

> Nothing wrong with this, but let me note that random effect at sampling
unit level is optional to include (rather than "forced by study
design"), and it should be included only if you are interested in
co-occurrence patterns at that level

I'm interested in species-species associations estimated from the Omega matrix. I think it's the way to estimate them, right ?

`sampling_design$sample` is a character vector, I thought there was I thought there was some [coercion to factor](https://github.com/hmsc-r/HMSC/blob/46fd1c4ccdf79f24563ecb3b19a7c669a0dc49b0/R/HmscRandomLevel.R#L76-L82).

**Comment by ovaskain** [comment]
>Sorry, I've made a mistake, I've only 20 environmental variables.

Ok - but this is a lot as well, so you are having a major variable 
selection problem, which is highly non-trivial for JSDM. I suggest that, 
at least to start with, you start with at most 5 covariates (based on 
some pre-selection method). Once you have results for this, you may go 
back to the variable selection problem.

 >I'm interested in species-species associations estimated from the 
Omega matrix. I think it's the way to estimate them, right ?

Yes!

If you still encounter the error, send me the code and data that 
reproduces it, so I will have a look.

Otso

**Comment by clementviolet** [comment]
Hi!

I tried to implement the different solutions you proposed, but none of them worked. I tried the following solutions:
- Change the format of the environmental effects  data frame to a matrix;
- Coerce the random effects string vector into a factor;
- Reduce the number of environmental variables to seven.

Each time I get the same error message (except I coerced the environmental data frame to a matrix, because It should be a data frame).

I've send you an email with the data and the code.

Clément

**Comment by ovaskain** [comment]
Hi Clement,

The columns of the study design need to be factors. I added the 
following line to your code and then it run without error:

sampling_design$sample = as.factor(sampling_design$sample)

Best,

Otso

**Comment by clementviolet** [comment]
Hi Otso!

Thanks for your quick answer, I was (wrongly) thinking that if I coded something like this it was enough:

rL <- HmscRandomLevel(units = as.factor(sampling_design$sample))

I guess `studyDesign` argument is used somehow to compute the predicted values and was causing my bug, right?

Thanks again for your time helping me.

I hope to see you online in November for your course.

Regards,

Clément

**Comment by ovaskain** [comment]
Hi,

 >Thanks for your quick answer, I was (wrongly) thinking that if I coded 
something like this it was enough

 >rL <- HmscRandomLevel(units = as.factor(sampling_design$sample))

 >I guess `studyDesign` argument is used somehow to compute the 
predicted values and was causing my bug, right?

Indeed, when you define the study design for the Hmsc object as 
"studyDesign = sampling_design", then sampling_design$sample should be a 
factor, exactly in the same way as when defining rL.

Otso
