### ISSUE TITLE
defining spatial structure in nested or spatially clustered sampling design

### ISSUE THREAD

**Issue by ewmorr** [hmsc-r/HMSC#49]
Hi,

Thanks for the excellent package and many excellent papers describing the methods. I have been working to properly specify spatial random effect in a nested sampling design. I think I have the random effects specification worked out, but wanted to pose this as a question (hopefully I'm not missing something obvious in the vignettes/help documentation). There appear to be similar issues raised in #47 and may be similar in principle to the "islands in an ocean" model described in #33  though I did not see syntax there.

I have a nested sampling design, wherein multiple samples were taken per site, and each site has a single set of GPS coordinates, i.e. no coordinates for individual samples. (These are microbial communities of trees within ~1 ha plots/sites, where the sites are distributed from 200-1000 km distance from each other.)

I first tried specifying the spatial random effect so that each sample had a set of coordinates, with coordinates for samples within a site repeated, but this resulted in a `Error in chol.default(W) : the leading minor of order n is not positive definite` error. (Note: this works with coordinates jittered.) I next tried to specify the spatial effect at the level of site, with a site random effect (i.e., one coordinate row for each site, with row names of the spatial matrix designated by site), and this results in the function running.

Following code gives the error
```
library(Hmsc)
library(MASS)
set.seed(6)

n = 100
ns = 2

#coordinates for each site, and also coordinates for each sample (that are the same for all samples within a site
plot_coords = matrix(runif(2*10), ncol = 2)
xycoords = matrix(rep(t(plot_coords),10),ncol=2, byrow = T)

colnames(xycoords) = c("x-coordinate","y-coordinate")
rownames(xycoords) = paste0("sample_", seq(1:n))
colnames(plot_coords) = c("x-coordinate","y-coordinate")
rownames(plot_coords) = paste0("site_", letters[seq(1:10)])

#toy data following vignette
beta1 = c(-1,1)
alpha = rep(0,ns)
beta = cbind(alpha,beta1)
x = cbind(rep(1,n),rnorm(n))
Lf = x%*%t(beta)
sigma.spatial = c(2)
alpha.spatial = c(0.35)
Sigma = sigma.spatial^2*exp(-as.matrix(dist(xycoords))/alpha.spatial)
eta1 = mvrnorm(mu=rep(0,n), Sigma=Sigma)
lambda1 = c(1,2)
Lr = eta1%*%t(lambda1)
L = Lf + Lr
yprob = 1*((L +matrix(rnorm(n*ns),ncol=ns))>0)
XData = data.frame(x1=x[,2])

#Study desgin, random effect, and model specification
studyDesign = data.frame(
    sample = as.factor(paste0("sample_", seq(1:n))),
    site = as.factor(paste0("site_", letters[seq(1:10)])),
    spatial = as.factor(paste0("sample_", seq(1:n)))
)

rL.sample = HmscRandomLevel(units = as.factor(studyDesign$sample))
rL.site = HmscRandomLevel(units = as.factor(studyDesign$Site))
rL.spatial = HmscRandomLevel(sData = xycoords)

m.spatial = Hmsc(Y=yprob, XData=XData, XFormula=~x1,
studyDesign=studyDesign, ranLevels=list("sample"=rL.sample, "site" = rL.site, "spatial" = rL.spatial),distr="probit")

m.spatial = sampleMcmc(m.spatial, thin = 1, samples = 10, transient = 5,
nChains = 2, verbose = 0,updater=list(GammaEta=FALSE))

#Error in chol.default(W) : 
#  the leading minor of order 3 is not positive definite
```
Respecifying the spatial rL and studyDesign works
```
#redefine spatial random effect on plots and redefine studyDesign
rL.spatial = HmscRandomLevel(sData = plot_coords)

studyDesign = data.frame(
sample = as.factor(paste0("sample_", seq(1:n))),
site = as.factor(paste0("site_", letters[seq(1:10)])),
spatial = as.factor(paste0("site_", letters[seq(1:10)]))
)

m.spatial = Hmsc(Y=yprob, XData=XData, XFormula=~x1,
studyDesign=studyDesign, ranLevels=list("sample"=rL.sample, "site" = rL.site, "spatial" = rL.spatial),distr="probit")

m.spatial = sampleMcmc(m.spatial, thin = 1, samples = 10, transient = 5,
nChains = 2, verbose = 0,updater=list(GammaEta=FALSE))
```

So, questions:

1. Is spatial effect at site level as done in the second code block the appropriate syntax for an "islands in an ocean"/spatially clustered or nested sampling design?

2. It seems like row names of the various objects are important here. Is that the case, and at what levels are the row names used to associate data points within different objects? E.g., it clearly seems that the row names of `plot_coords` in the second code block need to be coded to site, but do the row names of the `yprob` matrix need to be coded to sample?

Thanks for any pointers!
~Eric

**Comment by ewmorr** [comment]
Based on explanation in #47 updating here. (I see now that is likely the same issue but wasn't following the thread there...)

Using data from above, and defining a random effect of sample (for species co-occurence at sample level) and spatially structured random effect of site:

```
n_sites = 10

plot_coords = matrix(runif(2*n_sites), ncol = 2)
rownames(plot_coords) = paste0("site_", letters[seq(1:n_sites)])

studyDesign = data.frame(
    sample = as.factor(paste0("sample_", seq(1:n))),
    site_spatial = as.factor(
        rep( paste0("site_", letters[seq(1:n_sites)]), 10)
    )
)

rL.sample = HmscRandomLevel(units = paste0("sample_", seq(1:n)))
rL.site_spatial = HmscRandomLevel(sData = plot_coords)

m.spatial = Hmsc(Y=yprob, XData=XData, XFormula=~x1,
studyDesign=studyDesign, ranLevels=list("sample"=rL.sample, "site_spatial" = rL.site_spatial),distr="probit")

m.spatial = sampleMcmc(m.spatial, thin = 1, samples = 10, transient = 5,
nChains = 2, verbose = 0,updater=list(GammaEta=FALSE))
```

**Comment by microbluvrsarah** [comment]
Hello!! Hate to revive an old thread, but I just want to make sure I am understanding correctly! My understanding is that once you include the spatial information for your plots, we are now analysing the spatial auto-correlation related to the plots, and are no longer looking at plot ID as categorical random variables (it doens't seem possible to include both types anyway). And then you included sample ID as a random level to look at species co-occurence at the sample level (as you have said). But, if I wanted to look at species co-occurence at plot level, can this be revealed with the site_spatial code, and could I skip the sample-level random effect entirely? 

Thank you!!

> Based on explanation in #47 updating here. (I see now that is likely the same issue but wasn't following the thread there...)
> 
> Using data from above, and defining a random effect of sample (for species co-occurence at sample level) and spatially structured random effect of site:
> 
> ```
> n_sites = 10
> 
> plot_coords = matrix(runif(2*n_sites), ncol = 2)
> rownames(plot_coords) = paste0("site_", letters[seq(1:n_sites)])
> 
> studyDesign = data.frame(
>     sample = as.factor(paste0("sample_", seq(1:n))),
>     site_spatial = as.factor(
>         rep( paste0("site_", letters[seq(1:n_sites)]), 10)
>     )
> )
> 
> rL.sample = HmscRandomLevel(units = paste0("sample_", seq(1:n)))
> rL.site_spatial = HmscRandomLevel(sData = plot_coords)
> 
> m.spatial = Hmsc(Y=yprob, XData=XData, XFormula=~x1,
> studyDesign=studyDesign, ranLevels=list("sample"=rL.sample, "site_spatial" = rL.site_spatial),distr="probit")
> 
> m.spatial = sampleMcmc(m.spatial, thin = 1, samples = 10, transient = 5,
> nChains = 2, verbose = 0,updater=list(GammaEta=FALSE))
> ```
