### ISSUE TITLE
Trying to identify efficiency bottlenecks/solutions

### ISSUE THREAD

**Issue by J-D-J-Clare** [hmsc-r/HMSC#53]
Hi,

First, just wanted to congratulate the developers--Hmsc is a really useful and flexible tool.

I had a general question about scalability/speed and different model components, and I apologize in advance for the rambling/uncertain nature of the question. I am attempting to fit probit models for about 25 species across about 1200 spatial replicates ('plots') nested within ~400 larger spatial clusters ('grids'). Each plot has been sampled multiple times (ranging from ~ 5 to ~300), such that at the finest temporal resolution, the Y matrix has dimension 25 species x 216,000 'samples'.  The key questions relate to how species occurrence and co-occurrence respond to a few spatiotemporally varying covariates. The model structure I have been trying to pursue includes between 5-10 covariates in X, 2-3 trait effects upon Beta, and 2-3 covariates associated with Lambda.  There are 3 random levels I've specified:

rL1=HmscRandomLevel(units=MyStudyDesign$plot)
rL2= HmscRandomLevel(sData=GridCoords, sMethod = 'NNGP') 
rL3= HmscRandomLevel(xData=data.frame(x1=rep(1, 216000),x2=XDAT$X2, X3=XDAT$X3))

Not really surprising but I've found that incorporating rL3 really slows things down (maybe ~100 samples every several days). I can condense the data some by aggregating temporal replicates ('samples'), discarding species, or discarding locations. I've found that cutting the number of rows in the Y matrix  to about 40000 speeds sampling up somewhat, but maybe not sufficiently for the particular pending deadlines.

 I suppose my question is whether there are certain model components where dimension reduction is likely to exhibit the most pronounced gains? Or alternatively/additionally, is there a different general way to approach spatiotemporal environmental variation in co-occurrence that might be more effective? I've considered the A matrix described in the 2017 introductory paper, but am a little worried about drastically increasing the number of estimated coefficients (to be somewhat analogous to environmental variation in lambda would seem to require interactions between the A matrix and some covariates).  I am also not quite sure how to deal with the ragged nature of the sampling--in many cases, there are gaps in the time-series, and it seems like the A matrix would have to be imputed? 

Thanks again for the excellent software.

John

**Comment by ovaskain** [comment]
Hi,

1) For your rL1, it is safer to add levels and thus have

rL1=HmscRandomLevel(units=levels(MyStudyDesign$plot))

2) Just to check that the number of rows in GridCoords should be 400, 
not 216,000

3) In rL3 you are modelling how residual species occurrences at the 
sample level behave as a function of X2 and X3. This is quite an 
involved and complicated model, and your data are quite big (in terms of 
sampling units but "luckily" not in terms of number of species), so not 
surprising if you have problems in convergence or computational times. 
The more basic model would have X2 and X3 only in XData and then model 
rL3 as rL3= 
HmscRandomLevel(units=data.frame(as.factor(sample=1:216000))). This 
model would ask how occurrences depend on X2 and X3, and also 
co-occurrences through their dependency on occurrences. But that would 
only estimate the mean residual co-occurrence (on top of that expected 
based on occurrences), not how that depends on X2 and X3. Even if you 
are interested in the more refined question, I would start from this 
model, and first fit for smaller subset of data, to be 100% sure you 
know which model you wish to fit and why before moving to the final model.

Hope this helps to continue!

Otso

**Comment by J-D-J-Clare** [comment]
Thanks, Otso! This was helpful. rL1 and rL2 were coded and behaving as expected. Your explanation as to why rL3 presents issues makes complete sense.
