### ISSUE TITLE
Computing species associations and predictions with a spatial random effect model

### ISSUE THREAD

**Issue by cabuelow** [hmsc-r/HMSC#58]
Hello,

I have an hmsc model (probit) with 149 sampling units, 50 species, 16 covariates, 1 spatial random level, and five latent factors. The hmsc model object is stored as 'm.spatial'.

When I try to compute species associations using the following:
```r
OmegaCor <- computeAssociations(m.spatial)
I get the following error: 
Error in seq.default(start, length(chain), thin) : 
  wrong sign in 'by' argument
```
Similarly when I try to calculate predictions with the following:
```r
predY <- predict(m.spatial, XData=Gradient$XDataNew, studyDesign=Gradient$studyDesignNew,
                ranLevels=Gradient$rLNew, expected=TRUE)
```
I get the same error as above.
Is there any advice for trouble-shooting this error?

Many thanks,
Christina

**Comment by jarioksa** [comment]
I cannot reproduce this, and cannot fix things that I cannot reproduce. However, the ultimate error comes from `seq` function. What were the values of `transient`, `samples` and `thin` in your `sampleMcmc` command?

**Comment by jarioksa** [comment]
Do you have only one chain? I can confirm, that these functions fail if you only have one chain. However, I would like to know if this is the case with you.

**Comment by jarioksa** [comment]
We need a reproducible example.

**Comment by jarioksa** [comment]
Hello, I could have this exact error if I haven't run `sampleMcmc`. That is, you must first define your model with `Hmsc()`, then you must run `sampleMcmc()` to get the posterior samples. Functions like `computeAssociations()` and `predict()` use those posterior samples. Have you run `sampleMcmc`?

**Comment by cabuelow** [comment]
Thanks Jari, sorry I just haven't had time to put up a reproducible example yet. But yes, I have run sampleMcmc, and all other functions for extracting, summarising, and evaluating the posterior samples work perfectly.

I'll try to get a reprex up in the next few days, in the meantime, here are the Hmsc and sampleMcmc commands I've been using:

# specify hmsc model

xycoords <- as.matrix(dat %>% dplyr::select(X,Y))
colnames(xycoords) <- c('x-coordinate', 'y-coordinate')
row.names(xycoords) <- 1:nrow(dat)
y <- as.matrix(dat %>% dplyr::select(Australasian.Darter:Australian.Shelduck))
x <- dat %>% dplyr::select(Agricultural_Water_Stress:Wetland_Disconnectivity, ele_mt_sav, tmp_dc_syr, pre_mm_syr)
formula <- paste0(colnames(x), collapse = '+')
studyDesign <- data.frame(sample = as.factor(1:nrow(dat)))
rL.spatial <- HmscRandomLevel(sData = xycoords)
rL.spatial <- setPriors(rL.spatial, nfMin=3, nfMax=10) # here set number of LVs (3-10)

m.spatial <- Hmsc(Y = y, XData = x, 
                 XFormula = ~Agricultural_Water_Stress+Aquaculture_Pressure+Dam_Density+
                   Livestock_Density+Nitrogen_Loading+Pesticide_Loading+Phosphorus_Loading+
                   Potential_Acidification+Sediment_Loading+Soil_Salinisation+Thermal_Alteration+
                   Wetland_Disconnectivity+ele_mt_sav+tmp_dc_syr+pre_mm_syr,
                 studyDesign = studyDesign, 
                 ranLevels = list('sample' = rL.spatial), 
                 distr = 'probit')

# set mcmc sampling parameters

nChains <- 2
test.run <- FALSE
if (test.run){
  # with this option, the vignette runs fast but results are not reliable
  thin = 1
  samples = 10
  transient = 5
  verbose = 0
} else {
  # with this option, the vignette evaluates slow but it reproduces the results of
  # the .pdf version
  thin = 10
  samples = 1000
  transient = 8000
  verbose = 1 # set to 0 to suppress output reporting how MCMC sampling is proceeding
}

# run model

set.seed(123)

system.time( # takes 20 mins to run for 50 spp, 21 covars (1000 samples, 2 chains, 10 thinning, 1000 burnin)
m.spatial <- sampleMcmc(m.spatial, thin = thin, samples = samples, transient = transient,
                       nChains = nChains, verbose = verbose, updater=list(GammaEta=FALSE))
)

**Comment by cabuelow** [comment]
Hi Jari, I loaded the saved m.spatial model object mentioned above, and tried running the 'computeAssociations' and 'predict' functions again, and this time they worked perfectly and I did not receive the error messages I posted. 

Apologies for taking your time on this, and thanks very much for your help - I'm enjoying using the HMSC package.

**Comment by jarioksa** [comment]
This seems to be settled down.
