### ISSUE TITLE
Is there a way to calculate species covariance without a random effect?

### ISSUE THREAD

**Issue by Djeppschmidt** [hmsc-r/HMSC#60]
Hello, and thanks so much for creating this package. I am very excited about using it and have been spending a lot of time trying to really understand how it works.

My question after going through the tutorials is that the computePredictedValues function requires an Hmsc input object with different random effect levels. I have a dataset for which I have covariates and a treatment variable (with 5 levels). I'm interested in the covariance of my species data; to calculate the covariance, I need to use my treatment variable as the random effect, so in effect I need to run the model twice. Once to get the estimates for the treatment effect on the species, and once to get the covariance matrix. Is there a way to calculate species covariance on a model that doesn't have a random variable? Or if there isn't, I was wondering if there's a reason why this is not possible?

Thanks,
Dietrich

**Comment by ovaskain** [comment]
The covariance matrices that HMSC outputs are specific to each random 
level included. Would be possible to compute such also for fixed 
effects, as well as the sum of fixed and random effects. Probably we 
should implement such functions at some point, as also others have asked 
about this.

Best,

Otso
