### ISSUE TITLE
Factors levels in constructGradient() and labels in plotGradient()

### ISSUE THREAD

**Issue by rburner** [hmsc-r/HMSC#63]
Hi All,

Thanks again for the HMSC package! I noticed something in the constructGradient() and plotgradient() functions that causes an issue for factor covariates. When I construct a gradient with a focal variable that is a factor, the levels of that factor get re-ordered alphabetically in the gradient dataframe. (I sometime have ordered the factors non-alphabetically in the model XData, often to put them in some kind of logical order). 

The plotGradient() function then orders the predictions of the factors on the x-axis according to the factor level order in the gradient, and appears to label those factors correctly. But, the raw data, when plotted, are plotted in the order of factor levels in the model (and so aren't always matched with the correct factor level in the plot).

The predict() function doesn't appear to be affected by factor level order in the gradient, which is good (so I guess it uses the actual factor level names rather than numbers).

The example plots below illustrate this. In the first plot, which is correct, I've reordered the factor levels in the Gradient to match the model XData prior to using predict(). In the second plot, I've arbitrarily reordered the factor levels in the gradient; you can see that the estimates, whiskers, and axis labels stay the same for each factor level, but the relative x-axis positions change. The problem though is that the raw data (which are now incorrectly placed) do not move to follow the factors. (I didn't use the default alphabetic factor order in the 2nd example plot below, because the difference in the plots is harder to see for these data. But the same principle applies)

Maybe some code in constructGradient() that reordered the factor levels to match the XData would fix this?

Thanks,
Ryan  

![ex1](https://user-images.githubusercontent.com/36172156/98357587-b6f01c00-2025-11eb-9943-0237d47e34a2.png)
![ex2](https://user-images.githubusercontent.com/36172156/98357606-bd7e9380-2025-11eb-9a51-441737406235.png)

**Comment by jarioksa** [comment]
You should order the levels of your factors programmatically. See help of factor, and there levels= argument to see how this happens. It doesn’t help to re-order them manually in a data matrix, because the factors will be ordered when interpreting the formula for the analysis.

Cheers, Jari Oksanen

**Comment by rburner** [comment]
Thanks @jarioksa 

I'm not sure if I was clear though, or if I'm understanding your comment exactly. I am talking about how the factor levels are ordered (whether by default, or manually through the levels= argument). I sometime order the levels manually in my input data in order to have a certain level be the intercept in the model output.

My comment above refers to the constructGradient function in HMSC. It, as I'm sure you know, creates a new dataframe for making predictions from the fitted model. My point is just that the factor levels in this gradient will be ordered by default by HMSC, rather than reflecting their order in original input data, and that this can cause problems in plotting. So I'm talking about the factor levels order, not their order in rows of the data matrix.

Make sense?

**Comment by jarioksa** [comment]
`constructGradient`  and other functions honour the **R** method of ordering the levels of factors. If you want to change the ordering, you must do it in base **R**: use `levels=` argument to set the order of factor levels, and that will be used in *all*  **R** functions, including `constructGradient`.  This is the only way.

**Comment by rburner** [comment]
@jarioksa Thanks - yes, I know that. The issue is that when constructGradient orders the factor levels it does it 'from scratch' using R defaults rather than by matching their order to their original order in the model object that constructGradient is using to construct the gradient. 

It seems to me that ideally the constructGradient function should order factor levels to match their order in the original model so that users can use the canned constructGradient and plotGradient functions back-to-back without plotting errors, regardless of whether they chose to order factors in the original model by default or according to some other logical scheme.

**Comment by rburner** [comment]
I've envisioning a line of code added to the end of the constructGradient() function along these lines, for cases in which  focalVariable is a factor:

`Gradient$XDataNew[,1]=factor(Gradient$XDataNew[,1],levels(Gradient$XDataNew[,1])[match(levels(Gradient$XDataNew[,1]),levels(m$XData[,which(names(m$XData)==focalVariable)]))])
`

**Comment by jarioksa** [comment]
@rburner I can see now what you meant. I pushed a quick fix to github. Please check if this fixes the problem.

**Comment by rburner** [comment]
@jarioksa Jari, great, that works!!
