### ISSUE TITLE
installation error for vignettes

### ISSUE THREAD

**Issue by dougwyu** [hmsc-r/HMSC#7]
`install_github("hmsc-r/HMSC", build_opts = c("--no-resave-data", "--no-manual"))`, produces this error:

> ✔  checking for file ‘/private/var/folders/4g/4wpmdzbd7tj0cwctcd99wz680000gp/T/RtmpQVtgTN/remotes102f511d44a89/hmsc-r-HMSC-077cb8c/DESCRIPTION’ ...
> ─  preparing ‘Hmsc’:
> ✔  checking DESCRIPTION meta-information ...
> ─  installing the package to build vignettes
> E  creating vignettes (10.2s)
>    duplicated vignette title:
>      ‘R packages: Static PDF and HTML vignettes’
>    
>    --- re-building ‘vignette_1_univariate.pdf.asis’ using asis
>    --- finished re-building ‘vignette_1_univariate.pdf.asis’
>    
>    --- re-building ‘vignette_2_multivariate_low.pdf.asis’ using asis
>    --- finished re-building ‘vignette_2_multivariate_low.pdf.asis’
>    
>    --- re-building ‘vignette_3_multivariate_high.pdf.asis’ using asis
>    --- finished re-building ‘vignette_3_multivariate_high.pdf.asis’
>    
>    --- re-building ‘vignette_4_simulated.pdf.asis’ using asis
>    --- finished re-building ‘vignette_4_simulated.pdf.asis’
>    
>    --- re-building ‘vignette_5_birds.pdf.asis’ using asis
>    --- finished re-building ‘vignette_5_birds.pdf.asis’
>    
>    Error: Duplicate vignette titles.
>      Ensure that the %\VignetteIndexEntry lines in the vignette sources
>      correspond to the vignette titles.
>    Execution halted
> Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
>   System command error

These install successfully (no vignettes, but they can be downloaded from github anyway):

`install_github("hmsc-r/HMSC")`
`install_github("hmsc-r/HMSC", build_opts = c("--no-resave-data", "--no-manual", "--no-build-vignettes"))`

**Comment by gtikhonov** [comment]
I decided to close this, since there have been major changes regarding the distribution of the package.
