### ISSUE TITLE
are the GPP or NNGP methods for spatial random effects implemented in R?

### ISSUE THREAD

**Issue by FabianRoger** [hmsc-r/HMSC#72]
The book mentions [this article](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecy.2929)[1] for a computationally more efficient implementation for spatial random effects with many sites. 

The article mentions that the methods have been implemented in the Matlab version of HMSC but doesn't mention the R version. Has this been implemented yet? 

1. Tikhonov G, Duan L, Abrego N, Newell G, White M, Dunson D, et al. Computationally efficient joint species distribution modeling of big spatial data. Ecology. 2020;101(2):e02929.

**Comment by MelindadeJonge** [comment]
Hi Fabian, 

Both methods are included in the R version. Please have a look at vignette 4, which describes how to run spatial models with these methods. 

Cheers, 
Melinda

**Comment by FabianRoger** [comment]
Thanks! 

If someone comes across this, here is how to call the vignette: 

```
vignette("vignette_4_spatial", package = "Hmsc")
```
