### ISSUE TITLE
Temporal random effect

### ISSUE THREAD

**Issue by clementviolet** [hmsc-r/HMSC#75]
Hi everyone, for some hours now, I try to set a temporal random effect.

I have the following `studyDesign` data frame.

| Year  | Site   |  Habitat |
| ------------- | ------------- |------------- |
| 2006          | Site_1           | Rocky_shore | 
| .... | ... | ... |
| 2014 | Site_21 | Eelgrass |

In total I've got 12 years of sampling, 21 sites and 2 different habitats. Not all sites were sampled every year and not all sites have both habitats.

Here's what I'm doing:

```r
rL1<- HmscRandomLevel(sData = as.matrix(unique(studyDesign$Year)))
rL2 <- HmscRandomLevel(units = unique(studyDesign$Site))
rL3 <- HmscRandomLevel(units = unique(studyDesign$Habitat))

m <- Hmsc(Y = as.matrix(Y), XData = XData,  XFormula = XFormula,
         distr="probit", studyDesign=studyDesign, ranLevels = list(Year = rL1, Site = rL2, Habitat = rL2))

thin <- 20
samples <- 1000
nChains = 3

fitted <-  sampleMcmc(m, samples = samples, thin = thin,
               nChains = nChains, nParallel = 1)
```

I have got the following message when `sampleMcmc()` runs:

```
Error in chol.default(W) : 'a' must have dimensions > 0
```
I think I misdefined the random effect.

Thank you in advance!

**Comment by ovaskain** [comment]
You need to have the units (e.g. "1987") as rownames, and the values 
(e.g. 1987) as the column of the sData matrix. Do you have access to the 
book? See page 293 for an example of temporal random effect.

O2

**Comment by clementviolet** [comment]
Hi, thank you for the advice about the rownames of the sData matrix. I didn't understant that `Year` needed to be a factor in the `samplinDesign` data frame.
