### ISSUE TITLE
Error in Eta[[r]][as.character(dfPiNew[, r]), ] : no 'dimnames' attribute for array

### ISSUE THREAD

**Issue by DominiqueMaucieri** [hmsc-r/HMSC#81]
Hi,

I have been putting together a model for coral communities and I keep getting an error message from computePredictedValues

The message is 
` Error in Eta[[r]][as.character(dfPiNew[, r]), ] : no 'dimnames' attribute for array `

My model code is 

` model_1 <- Hmsc(Y=HMSC_2013_coral_pa, studyDesign = studyDesign, ranLevels = list(sample = rL), XData = HMSC_2013_XData, XFormula = ~Disturb, distr = "probit") `

`#MCMC details
nChains = 2
thin = 100
samples = 1000
transient = 50*thin
verbose = 50*thin`

`model_1 = sampleMcmc(model_1, thin = thin, samples = samples, transient = transient, nChains = nChains, nParallel = nChains, verbose = verbose)`

`preds = computePredictedValues(model_1)
evaluateModelFit(hM = model_1, predY = preds) `

I'm guessing there is an issue with how I have set up my data frames but I am stuck with how to fix this error.

Thanks in advance for your insight.
Dom

**Comment by DominiqueMaucieri** [comment]
Additionally, I get the same error message when working through vignette #3 from the Hmsc package

**Comment by jarioksa** [comment]
My bet is (again) that somewhere (studyDesign, ranLevels) you have unit names that are not factors (like they are required to be), but character strings (which will give various errors). Please check these.

As to vignette fairlue: I don't get any error when rebuilding vignette 3 from the source. Please check that you have factors where you need to have them.
