### ISSUE TITLE
Unclear need for extra return value

### ISSUE THREAD

**Issue by gtikhonov** [hmsc-r/HMSC#9]
@ovaskain , I have a concern about this change you've implemented. This is about `L` value that you changed to be outputted from the `updateZ` method and later saved to the posterior. This value is deterministically derived from other model parameters and data. It also is asymptotically the largest element saved to the posterior, and it makes the fitted model almost 2 times larger. Are you sure there is no way to avoid saving this non-essential information?
https://github.com/hmsc-r/HMSC/blob/066ec07f7ded49b92fe980f7f06981125c91064c/R/updateZ.R#L119

**Comment by hmsc-r** [comment]
The value of L returned by updateZ is the likelihood of the data, and is needed for computation of WAIC (and perhaps other things). Could surely be computed later from the posterior as well, but thought it is handy to compute in updateZ as is easy to do there. L should be just a list of numbers of length ny (number of sampling units; as it is the likelihood jointly for all species), so it should be smaller than e.g. the eta:s for random effects. I probably misunderstand something: why does it take so much space? In any case, I am happy with alternative implementations.

**Comment by gtikhonov** [comment]
@hmsc-r , Ok, now I see that it is indeed much smaller than the whole Y/Z matrix. My bad that I did not figure it out straightaway.

Well, I am still do not fully agree that we indeed need to compute those values in `updateZ` method, since
1. These values can be recomputed given sample of all other model parameters.
2. So far these values are used only for WAIC.
3. Obtaining these values takes certain computational effort (and therefore increases MCMC time) and we anyway discard them straightaway for those posterior samples that are thinned out.
4. For some post processing methods, e.g. conditional predictions we need to make `updateZ` calls, but we do not need these log-likelihood values.

Summarising everything above, I believe that it would be more natural and computationally efficient to separate the log-likelihood calculations to a separate function, which can be called from those methods that really require these values.

P.S. The log-likelihoods are currently not computed for log-poisson model. Maybe, some analytical formula also exists for that case, but I do not know it at this moment. However, such likelihood is easy to compute with Gauss-Hermite quadrature approximation of the corresponding integral. Do you think it is worthy to add it?

**Comment by ovaskain** [comment]
I agree it is better to do it in post-processing. Once reason why I put it to updateZ was that I did not want to replicate same pieces of code in many places. To avoid this, we could write functions computeLFix, computeLRandom, computeLRRR, and computeL, which basically sums the three. Then these functions can be called from many places (not only updateZ, but also in many other update functions, and also predict functions), which would avoid repetition and thus e.g. the possibility that we have two different versions of how fixed effects are computed. If you agree, I can implement this at some point. If you would implement the (approximate) likelihood for Poisson models, that would be great.
