### ISSUE TITLE
Trouble with hurdle model/ For loop

### ISSUE THREAD

**Issue by nanophyto** [hmsc-r/HMSC#91]
Hi,
I'm having some trouble with my Hurdle model in terms of the predictions. While trying to make the issue reproducible I've managed to pinpoint it down to the for loop. Without the loop the model is fine, but the same model in a for loop gives a standard deviation of zero...

[XData.csv](https://github.com/hmsc-r/HMSC/files/6337144/XData.csv)
[Y.csv](https://github.com/hmsc-r/HMSC/files/6337145/Y.csv)

```
XData = read.csv2("XData.csv")
Y = read.csv2("Y.csv")


nChains = 2
thin = 1
samples = 100*thin
transient = 500*thin
verbose = 500*thin
XFormula = ~ PAR + DIN + Silicate + Optical + Temperature

no_loop <-function(){
  Y = as.matrix(Y)
  Y[Y==0] = NA
  
  model = Hmsc(Y=Y, XData=XData, XFormula = XFormula,
               distr=  "normal", YScale = TRUE)
  
  m = sampleMcmc(model, thin=thin, samples =  samples, transient=transient, nChains=nChains,
                 verbose=verbose)
  
  
  preds = computePredictedValues(m)
  MF = evaluateModelFit(hM=m, predY=preds)
  print(MF)
}
#works fine:
no_loop()

with_loop <-function(){
  
  models = list()
  
  for (i in 1:2){
    Y = as.matrix(Y)
    if (i==1){Y = 1*(Y>0)}
    if (i==2) {
      Y[Y==0] = NA
    }
    models[[i]] = Hmsc(Y=Y, XData=XData, XFormula = XFormula,
                       distr= switch(i,  "probit", "normal"), YScale = TRUE)
  }
  
  m = sampleMcmc(models[[2]], thin=thin, samples =  samples, transient=transient, nChains=nChains,
                 verbose=verbose)
  
  preds = computePredictedValues(m)
  MF = evaluateModelFit(hM=m, predY=preds)
  print(MF)
}
#SD/RMSE = 0, R2 =NA
with_loop()
```

**Comment by jarioksa** [comment]
Look at this part of your `with_loop` code:
```r
  for (i in 1:2){
    Y = as.matrix(Y)
    if (i==1){Y = 1*(Y>0)}
    if (i==2) {
      Y[Y==0] = NA
    }
    models[[i]] = Hmsc(Y=Y, XData=XData, XFormula = XFormula,
                       distr= switch(i,  "probit", "normal"), YScale = TRUE)
  }
```
Now think about the values of `Y` in looping. In the first iteration (`i == 1`) the `Y` will be binary and have only values 0 and 1, and on the second iteration  (`i == 2`) you have this modified `Y` and you change  zeros to NA so that `Y` has only values 1 and NA. All non-NA values for the `"normal"` model are constant (1.0) and therefore you cannot fit a meaningful model.

**Comment by nanophyto** [comment]
Hi Jarioksa,

Many thanks, that makes sense. I modified the code from page 176 of the Join Species distribution modelling book, but I clearly should have thought it through more. 

Does the code of Joint Species on page 176 not also suffer from the same issue?
`studyDesign = data.frame(sample = data$LogID)
rL = HmscRandomLevel(units = studyDesign$sample)
models = list()
for (i in 1:3){
Y = as.matrix(YData)
if (i==2) {Y = 1*(Y > 0)}
if (i==3) {
Y[Y==0] = NA
Y = log(Y)
}
tmp = list()
for (j in 1:2){
XFormula = switch(j, ~1 + log(readcount),~DC +
log(readcount))
m = Hmsc(Y = Y, XData = XData, XFormula = XFormula,
studyDesign = studyDesign, ranLevels =
list(sample = rL), distr = switch(i,
“lognormal poisson”,“probit”,“normal”),YScale = TRUE)
tmp[[j]] = m
}
models[[i]] = tmp
}
`

**Comment by jarioksa** [comment]
No, it doesn't. This is the key line:
```r
Y = as.matrix(YData)
```
`YData` are unmodified and `Y` is copied from that unmodified data at every iteration, and only the copied `Y` is modified.
