### ISSUE TITLE
Standard deviation is zero warning in computeVariancePartitioning() for hurdle model

### ISSUE THREAD

**Issue by tbx200** [hmsc-r/HMSC#92]
I've fitted a hurdle model consisting of a probit PresAbs model and a log-transformed Abundance COP model with a normal distribution.

I've read the thread of Issue 91 [https://github.com/hmsc-r/HMSC/issues/91](url) but I don't think the same issue applies to my case as I don't split the data within a for-loop.

This is the code that I used for splitting the data:
```
Ypa = 1*(Y>0)
Yabu = Y
Yabu[Y==0] = NA
Yabu = log(Yabu)
```

Both Ypa and Yabu are large matrices in the R environment.

Then I fit my model with the following code (from the Hmsc course files):
```
m1 = Hmsc(Y=Ypa, XData = XData, XFormula=XFormula,
         phyloTree = phyloTree, 
         distr="probit", studyDesign=studyDesign,
         ranLevels=list(plot=rL.spat, year = rL.temp) )
m2 = Hmsc(Y=Yabu, XData = XData, XFormula=XFormula,
          phyloTree = phyloTree, 
          distr="normal", studyDesign=studyDesign,
          ranLevels=list(plot=rL.spat, year = rL.temp))

samples_list = c(250,250,250)
thin_list = c(1,10,100)
nChains = 6
for(Lst in 1:length(samples_list)){
  thin = thin_list[Lst]
  samples = samples_list[Lst]
  print(paste0("thin = ",as.character(thin),"; samples = ",as.character(samples)))
  nm = length(models)
  for (model in 1:nm) {
    print(paste0("model = ",modelnames[model]))
    m = models[[model]]
    m = sampleMcmc(m, samples = samples, thin=thin,
                   adaptNf=rep(ceiling(0.4*samples*thin),m$nr), 
                   transient = ceiling(0.5*samples*thin),
                   nChains = nChains,
                   nParallel = nChains,
                   updater = list(GammaEta=F)) 
    models[[model]] = m
  }
  filename = paste("models/models_thin_", as.character(thin),
                   "_samples_", as.character(samples),
                   "_chains_",as.character(nChains),
                   ".Rdata",sep = "")
  save(models,modelnames,file=filename)
}
```
I have no issues calculating model convergence and fit.
However, when I compute the variance partitioning, I get the same warning message for both models: 

> "In cor(lbeta[[i]][k, ], lmu[[i]][k, ]) : the standard deviation is zero"

The code I used for the VP computation:

```
m = models[[j]]
VP = computeVariancePartitioning(m)
```
With j either 1 or 2 in a for-loop.

**Comment by tbx200** [comment]
I see that at least one mistake is here:
```
Yabu[Y==0] = NA
```

should be: 
```
Yabu[Yabu==0] = NA
```

**Comment by jarioksa** [comment]
At this stage `Y == Yabu` so that both should give the same `Yabu` matrix: no problem there. However, the error message `the standard deviation is zero` hints to constant values in your model. We cannot see your data, but start by looking at values of `Ypa` and `Yabu`.

**Comment by tbx200** [comment]
Dear Jari,

Thanks for the quick response. I've looked at the summary of the matrices as well as histograms. Both matrices are as I would expect them: 0/1 for the Ypa matrix and values ranging from 0 to 6 for the log-transformed Yabu with depending on the rarity of the species a number of NA's. 
I'm working with the Swedish bird monitoring data and unfortunately, I am not allowed to share my data here.

**Comment by oysteiop** [comment]
Hi, I have seen this error often, and I think itæs simply due to ther enot being any trait in the data, hence the calculation of r2_traits fails (the correlation between the trait value and the regression slope). Perhaps Jari can try to fix this in the Hmsc code?

**Comment by tbx200** [comment]
Thank you Øystein. The R2T part of the variance partitioning object indeed has only NAs so I think that it indeed can be that.

**Comment by jarioksa** [comment]
@oysteiop @tbx200 Sorry for looking at this too hastily. Yes indeed, `R2T` is supposed  to give the _R_<sup>2</sup> related to traits, and if there are no traits this really should be `NA` (or traits are constant – which is the same thing). It is confusing to issue a warning, though, but otherwise the output is like it should be (_i.e._, `NA` – the statistic is Not Available when traits are Not Available).

**Comment by tbx200** [comment]
@jarioksa No need to apologize, thank you for the help in solving this.
I think the issue can be closed now.
