### ISSUE TITLE
error when multithreading on hpc

### ISSUE THREAD

**Issue by pyspider** [hmsc-r/HMSC#95]
Hi,
  I am not sure whether it's a hmsc issue here. While I tried to fit model on hpc (nParallel=4), I encountered this error:
> Error in unserialize(socklist[[n]]) : error reading from connection
> Calls: sampleMcmc ... recvOneData -> recvOneData.SOCKcluster -> unserialize
> Execution halted

Here is my code when I got the error.

> m1 = Hmsc(Y=Y, XData = X, XFormula = ~ temperature.month.mean + True_Altitude, phyloTree = mito.treepl, studyDesign = S, ranLevels=list(Site_ID=rL.spatial,date.circular=rL.date),distr="lognormal poisson")
> 
> #for test
> samples_list = c(200000)
> thin_list = c(1)
> nChains = 4
> models = list(m1)
> modelnames = c("whole_mitogenome_tree")
> 
> for(Lst in 1:length(samples_list)){
>   thin = thin_list[Lst]
>   samples = samples_list[Lst]
>   print(paste0("thin = ",as.character(thin),"; samples = ",as.character(samples)))
>   nm = length(models)
>   for (model in 1:nm) {
>     print(paste0("model = ",modelnames[model]))
>     m = models[[model]]
> m = sampleMcmc(m, thin = thin, samples = samples, adaptNf = rep(ceiling(0.4*thin*samples),m$nr), 
>            transient = ceiling(0.5*samples*thin), nChains = nChains, nParallel = nChains)
> models[[model]] = m}
> filename = file.path(model.directory, paste0("model_",modelnames[model],
>                                            "_chains_",as.character(nChains),
>                                            "_samples_",as.character(samples),
>                                            "_thin_",as.character(thin)))
> save(models,file = filename)
> }

I noted the hmsc require the LAPACK library on pthreds version (https://github.com/hmsc-r/HMSC/issues/23). Thus, I compiled R under openblas on pthreds version. Here is my R enviroment:

> sessionInfo()
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Red Hat Enterprise Linux Server 7.5 (Maipo)
> 
> Matrix products: default
> BLAS/LAPACK: /gpfs/software/OpenBLAS-0.3.9/lib/libopenblas_haswellp-r0.3.9.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.6.3

But I still get the same error. Many thanks for your help?

**Comment by pyspider** [comment]
Sure, it's not an issue for hmsc. I will colse this issue here. This error is caused because my hmsc run invoked oom-killer on hpc.

> Apr 28 21:30:01 cu40 systemd: Started Session 33266 of user root.
> Apr 28 21:30:01 cu40 systemd: Starting Session 33266 of user root.
> Apr 28 21:40:01 cu40 systemd: Started Session 33267 of user root.
> Apr 28 21:40:01 cu40 systemd: Starting Session 33267 of user root.
> Apr 28 21:48:54 cu40 kernel: R invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=0

**Comment by jarioksa** [comment]
Yup. I was just trying to look if there is something related to `Hmsc` in your message, but couldn't reproduce anything to that effect. However, one thing that you could try is to test with a bit smaller sample sizes: 200,000 is a lot and all those solutions will be saved on the disk (and first in the memory). The result object will be huge (I mean **HUGE**) and this can alert OS to do something for your job. Test first with smaller sample size, and rather thin than save 200,000 contiguous solutions.

**Comment by pyspider** [comment]
> Yup. I was just trying to look if there is something related to `Hmsc` in your message, but couldn't reproduce anything to that effect. However, one thing that you could try is to test with a bit smaller sample sizes: 200,000 is a lot and all those solutions will be saved on the disk (and first in the memory). The result object will be huge (I mean **HUGE**) and this can alert OS to do something for your job. Test first with smaller sample size, and rather thin than save 200,000 contiguous solutions.

> Thanks! I tried to test with a smaller sample sizes: 10. It was running smoothly. I can get the fitted model. Thus I submitted my hmsc run with 4 chains × 200,000 samples again on fat nodes (3T RAM per node).

**Comment by jarioksa** [comment]
Linux OOM-killer is triggered when you run out of memory: "It is the job of the linux 'oom killer' to sacrifice one or more processes in order to free up memory for the system when all else fails." (https://linux-mm.org/OOM_Killer)

I suggest thinning anyway. You won't gain much from having a huge number of strongly autocorrelated samples instead of smaller number of thinned independent samples.

**Comment by pyspider** [comment]
I want to make some decisions from this test (thin=1) later. If I won't gain much from this test run. I will increase a rather thin to get a smaller number of thinned independent samples. Many thanks for your suggestion again！
