### ISSUE TITLE
Making spatial predictions 

### ISSUE THREAD

**Issue by DottyTwente** [hmsc-r/HMSC#98]
Hi, I am exploring how to make spatial predictions from the HMSC model I fitted with 42 species presence and absences obtained from 155 locations. The prediction map, I presently have is just for the 155 points within the study area. There are a lot of empty gaps in the map. I extrapolated additional points and called it in as a new grid. However, I get an error message as stated below

 Error in data.frame(x = xy.grid[, 1], y = xy.grid[, 2], EpredY, C = XData.grid$curvature,  : 
  arguments imply differing number of rows: 36821, 155

N/B : 155 sampling units were used in fitting the HMSC model 

Secondly, i have a mask image of the study area, what line of codes can i use for making spatial predictions, because i have only seen spatial grids used.

Thank you
Dotty

**Comment by hmstorecenter-com** [comment]
Can i get thr image?
